[package]
name = "moonrun_wasmtime"
version = "0.1.0"
edition = "2021"
rust-version = "1.93"
publish = false

[[bin]]
name = "moonrun_wt"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
serde_json = "1.0"
wasmtime = { version = "45.0.0", features = ["gc-drc"] }

[profile.release]
opt-level = 3
lto = "thin"
