[package]
name = "xs-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
serde = { workspace = true, features = ["derive"] }
ordered-float.workspace = true
lazy_static.workspace = true
sha2.workspace = true