[package]
name = "interpreter"
version.workspace = true
edition.workspace = true

[dependencies]
xs_core.workspace = true
thiserror.workspace = true

[dev-dependencies]
parser = { path = "../parser" }
checker = { path = "../checker" }
