# similarity-rs configuration

# Minimum similarity threshold (0.0 - 1.0)
threshold = 0.90

# Minimum number of lines for a code block to be considered
min_lines = 5

# Maximum number of lines for a code block to be considered
max_lines = 200

# Directories to ignore
ignore_dirs = [
    "target",
    ".git",
    "node_modules",
    ".xs-codebase",
    "docs",
]

# File patterns to ignore
ignore_files = [
    "*.lock",
    "*.toml",
    "*.md",
    "*.wit",
    "LICENSE*",
]

# File extensions to check
include_extensions = [
    ".rs",
    ".xs",
]

# Output format
output_format = "text" # or "json", "markdown"

# Show context lines around duplicated code
context_lines = 3

# Group similar duplicates together
group_duplicates = true