[workspace]
members = [
    "xs_core",
    "parser",
    "checker",
    "interpreter",
    "cli",
    "xs_salsa",
    "perceus",
    "wasm_backend", "runtime", "codebase", "shell",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["XS Language Contributors"]

[workspace.dependencies]
xs_core = { path = "xs_core" }
parser = { path = "parser" }
checker = { path = "checker" }
interpreter = { path = "interpreter" }
thiserror = "1.0"
anyhow = "1.0"
clap = "4.5"
colored = "2.1"
criterion = "0.5"
wasmtime = "27.0"
wat = "1.219"
ordered-float = { version = "4.5", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
sha2 = "0.10"
im = "15.1"
hex = "0.4"
salsa = "0.16"
lazy_static = "1.5"

[package]
name = "xs-lang"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
xs_core = { path = "xs_core" }
parser = { path = "parser" }
checker = { path = "checker" }
interpreter = { path = "interpreter" }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "performance_benchmark"
harness = false

[[bench]]
name = "type_checker_bench"
harness = false
