[workspace]
members = [
    "xs_core",
    "parser",
    "checker",
    "interpreter",
    "cli",
    "xs_salsa",
    "perceus",
    "wasm_backend",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["XS Language Contributors"]

[workspace.dependencies]
xs_core = { path = "xs_core" }
parser = { path = "parser" }
checker = { path = "checker" }
interpreter = { path = "interpreter" }
thiserror = "1.0"
anyhow = "1.0"
clap = "4.5"
colored = "2.1"
criterion = "0.5"

[package]
name = "xs-lang"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
xs_core = { path = "xs_core" }
parser = { path = "parser" }
checker = { path = "checker" }
interpreter = { path = "interpreter" }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "performance_benchmark"
harness = false