# Clippy configuration for XS language project

# Allow some format args for readability
msrv = "1.70.0"

# Cognitive complexity threshold
cognitive-complexity-threshold = 30

# Too many arguments threshold
too-many-arguments-threshold = 10