[package]
name = "xs-compiler"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
xs-core = { path = "../xs-core" }
thiserror.workspace = true
ordered-float.workspace = true