[extension]
id = "vibe"
name = "Vibe"
description = "Vibe programming language support"
version = "0.1.0"
schema_version = 1
authors = ["mizchi"]
repository = "https://github.com/mizchi/vibe-lang"

[grammars.vibe]
repository = "https://github.com/mizchi/vibe-lang"
rev = "401ed58d1380f368a31ed628874b763a98bd146f"
path = "integrations/treesitter-vibe"
