id = "vibe"
name = "Vibe"
description = "Vibe programming language support"
version = "0.1.0"
schema_version = 1
authors = ["mizchi"]
repository = "https://github.com/mizchi/vibe-lang"

[grammars.vibe]
repository = "https://github.com/mizchi/vibe-lang"
rev = "d710185a72adfa62cbad5645a1be3f7f6d32ff7a"
path = "integrations/treesitter-vibe"
