[package]
name = "xs_salsa"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
xs_core = { path = "../xs_core" }
parser = { path = "../parser" }
checker = { path = "../checker" }
salsa = "0.17.0-pre.2"
thiserror.workspace = true
anyhow.workspace = true
