package xs:math_module@0.1.0;

interface exports {
  add: func(arg1: s64, arg2: s64) -> s64;
  subtract: func(arg1: s64, arg2: s64) -> s64;
  multiply: func(arg1: s64, arg2: s64) -> s64;
  divide: func(arg1: s64, arg2: s64) -> s64;
}

world math_module {
  export exports;
}
