package xs:math@0.1.0;

interface exports {
  add: func(arg: s64) -> s64;
  subtract: func(arg: s64) -> s64;
  multiply: func(arg: s64) -> s64;
  divide: func(arg: s64) -> s64;
}

world xs:math {
  export exports;
}
