[package]
name = "vibe-compiler"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
vibe-core = { path = "../vibe-core" }
thiserror.workspace = true
ordered-float.workspace = true
wasm-encoder = "0.219"
wit-component = "0.219"
wat.workspace = true