#!/usr/bin/env bash
# Borrow-spine census (#2733): how many `let` bindings hold a value through a
# WRAPPER -- a block or an if/match -- whose result spine hands back something
# the scope does not own? Measurement tool, not a gate.
#
#   bash scripts/borrow_spine_census.sh [flat-source.vibe]
#
# The default input is the flat self-compile source
# (lib/@vibe/compiler/_cli_adapter_module_source.vibe, regenerated by
# scripts/ensure_generated.sh). The probe
# (scripts/borrow_spine_census_probe.vibe) compiles through the committed seed
# like any `vibe test` file and prints one row per such `let`; the rows land in
# _build/borrow_spine_census/rows.tsv. Row format: see the probe's header.
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

input="${1:-lib/@vibe/compiler/_cli_adapter_module_source.vibe}"
if [ "$#" -eq 0 ]; then
  bash scripts/ensure_generated.sh >/dev/null
fi
[ -s "$input" ] || { echo "borrow_spine_census: input not found or empty: $input" >&2; exit 2; }

out_dir="_build/borrow_spine_census"
mkdir -p "$out_dir"
cp "$input" "$out_dir/input.vibe"

probe="scripts/borrow_spine_census_probe.vibe"
VIBE_TEST_QUIET_COMPILER_NOTE=1 bash scripts/vibe_test.sh "$probe" >/dev/null
wasm="_build/vibe_test/$(printf '%s' "${probe%.vibe}" | tr '/' '_').wasm"
[ -s "$wasm" ] || { echo "borrow_spine_census: probe wasm not produced: $wasm" >&2; exit 1; }
VIBE_PREOPEN_DIR="$ROOT_DIR" bash scripts/run_wasm_vibe_host_runner.sh --invoke _start "$wasm" > "$out_dir/rows.tsv"

echo "[borrow-spine-census] input=$input rows=$(wc -l < "$out_dir/rows.tsv") file=$out_dir/rows.tsv"
echo "[borrow-spine-census] by wrapper kind:"
awk -F'\t' '{ for (i = 1; i <= NF; i++) if ($i ~ /^top=/) print substr($i, 5) }' "$out_dir/rows.tsv" | sort | uniq -c | sort -rn
echo "[borrow-spine-census] worst spine leaf, BLOCK wrappers only (the class with no guard today):"
awk -F'\t' '{ t = ""; v = ""; for (i = 1; i <= NF; i++) { if ($i ~ /^top=/) t = substr($i, 5); if ($i ~ /^verdict=/) v = substr($i, 9) } if (t == "block") print v }' "$out_dir/rows.tsv" | sort | uniq -c | sort -rn
echo "[borrow-spine-census] worst spine leaf, if/match wrappers (value_has_borrowed_branch_tail already sees these):"
awk -F'\t' '{ t = ""; v = ""; for (i = 1; i <= NF; i++) { if ($i ~ /^top=/) t = substr($i, 5); if ($i ~ /^verdict=/) v = substr($i, 9) } if (t == "if" || t == "match") print v }' "$out_dir/rows.tsv" | sort | uniq -c | sort -rn
