#!/usr/bin/env bash
# The tree-sitter grammar ships as THREE artifacts generated from one grammar.js,
# and they are only correct together (#2409).
#
#   integrations/treesitter-vibe/src/parser.c   the C parser (grammar tests)
#   playground/public/tree-sitter-vibe.wasm     the playground editor
#   integrations/zed-vibe/grammars/vibe.wasm    the Zed extension
#
# Before #2403 they had always been regenerated in the same commit. #2403 added
# prefix `~` and could regenerate only the C parser -- `tree-sitter build --wasm`
# needs emscripten, which that environment did not have -- so the two wasm files
# went stale and `~x` stayed a syntax error in the playground and in Zed while
# the compiler and the corpus suite both accepted it. Nothing detected that; the
# pairing was a habit, not a check.
#
# It is a check now. The stamp records the hash each artifact had when they were
# last built together, so regenerating the C parser without rebuilding the wasm
# moves parser.c's hash off its stamp and fails here.
#
# What this gate does NOT prove: that the wasm implements the current grammar.
# Every value in the comparison lives in the tree, so restamping after a
# parser-only regeneration makes all three agree while the wasm is still stale
# (#2422 review reproduced that against this gate). Hashing cannot close it --
# scripts/check_treesitter_wasm_corpus.sh does, by parsing the corpus with each
# wasm, and scripts/stamp_treesitter_artifacts.sh refuses to write unless that
# passes. This gate is the cheap always-on half: it catches the pairing and the
# ABI without a node install.
#
# The second failure this gate catches is the ABI. `tree-sitter-cli` 0.24.x
# emits `LANGUAGE_VERSION 14` with a `.version` field; everything committed here
# is 15 with `.abi_version`. Generating with the wrong CLI produces a
# plausible-looking diff and NO error, silently downgrading the ABI for every
# consumer -- so the ABI is asserted from parser.c's own text, independent of
# what package.json happens to say.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="${VIBE_TREESITTER_ARTIFACTS_ROOT:-$(dirname "$SCRIPT_DIR")}"
cd "$ROOT"

STAMP="integrations/treesitter-vibe/generated.sha256"
PARSER_C="integrations/treesitter-vibe/src/parser.c"

# Expected ABI. Bumping this is a deliberate act: every consumer's loader has to
# accept the new number, so it does not get to move as a side effect of an
# `npm update` that nobody read.
EXPECTED_ABI=15

fail() { echo "[treesitter-artifacts] FAIL: $*" >&2; exit 1; }

# Probe by RUNNING it, not by `command -v`: a shim on PATH that dies on first
# use passes the lookup and fails the gate for an unrelated reason
# (scripts/ensure_seed.sh records the same trap).
sha256_of() {
  if sha256sum </dev/null >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  elif shasum -a 256 </dev/null >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    fail "sha256sum or shasum is required"
  fi
}

[ -f "$STAMP" ] || fail "missing stamp: $STAMP"
[ -f "$PARSER_C" ] || fail "missing generated parser: $PARSER_C"

# ---- 1. ABI, read out of the generated parser itself -------------------------
abi_line="$(grep -m1 '^#define LANGUAGE_VERSION ' "$PARSER_C" || true)"
[ -n "$abi_line" ] || fail "$PARSER_C declares no LANGUAGE_VERSION"
abi="${abi_line##* }"
if [ "$abi" != "$EXPECTED_ABI" ]; then
  fail "$PARSER_C is ABI $abi, expected $EXPECTED_ABI.
  tree-sitter-cli 0.24.x emits ABI 14 and 0.25.x emits 15. Regenerate with the
  version pinned in integrations/treesitter-vibe/package.json:
    cd integrations/treesitter-vibe && pnpm install && pnpm exec tree-sitter generate"
fi
# ABI 15 renamed the struct field. Checking the #define alone would pass a
# hand-edited number over a 0.24-shaped body.
if ! grep -q '\.abi_version = LANGUAGE_VERSION' "$PARSER_C"; then
  fail "$PARSER_C has no '.abi_version' field -- it was generated by a pre-0.25
  CLI (which spells it '.version') and the LANGUAGE_VERSION line disagrees with
  the body. Regenerate with the pinned tree-sitter-cli."
fi

# ---- 2. The three artifacts still hash to what they had when built together ---
# Read as `<sha256>  <path>`, the sha256sum output format, so the stamp can be
# refreshed with a plain `sha256sum ... > generated.sha256`.
# Each EXPECTED path must appear exactly once. Counting lines was a proxy for
# that and it broke exactly as a proxy does: a stamp that lost the Zed entry and
# gained a second playground entry still reached three, so the gate reported
# "3 artifacts match" while never looking at the Zed wasm at all -- measured
# with that wasm deliberately corrupted, and it still passed (#2422 review).
# A merge-damaged manifest could therefore disable one side of the very pairing
# this gate exists to enforce.
seen_parser=0
seen_play=0
seen_zed=0
while read -r want path; do
  case "$want" in ''|\#*) continue ;; esac
  [ -n "$path" ] || fail "malformed stamp line in $STAMP: missing path for $want"
  case "$path" in
    integrations/treesitter-vibe/src/parser.c)
      [ "$seen_parser" -eq 0 ] || fail "$STAMP lists $path more than once"
      seen_parser=1 ;;
    playground/public/tree-sitter-vibe.wasm)
      [ "$seen_play" -eq 0 ] || fail "$STAMP lists $path more than once"
      seen_play=1 ;;
    integrations/zed-vibe/grammars/vibe.wasm)
      [ "$seen_zed" -eq 0 ] || fail "$STAMP lists $path more than once"
      seen_zed=1 ;;
    *)
      fail "$STAMP stamps an unexpected path: $path
  The three artifacts are fixed. An entry outside them means the manifest was
  edited or merged by hand; regenerate it with
  scripts/stamp_treesitter_artifacts.sh." ;;
  esac
  [ -f "$path" ] || fail "stamped artifact is missing: $path"
  got="$(sha256_of "$path")"
  if [ "$got" != "$want" ]; then
    fail "$path drifted from the stamp in $STAMP
    stamped: $want
    actual:  $got
  These three artifacts are generated from one grammar and are only correct
  together. If you regenerated the C parser, rebuild both wasm files from the
  SAME src/ and restamp:
    cd integrations/treesitter-vibe
    pnpm install && pnpm exec tree-sitter generate
    pnpm exec tree-sitter build --wasm -o ../../playground/public/tree-sitter-vibe.wasm
    cp ../../playground/public/tree-sitter-vibe.wasm ../zed-vibe/grammars/vibe.wasm
    cd ../.. && bash scripts/stamp_treesitter_artifacts.sh
  The wasm build needs emscripten (emcc on PATH) or a running docker daemon.
  If you cannot build it, do not restamp -- leave this red, which is the state
  #2409 exists to make visible."
  fi
done < "$STAMP"

# A stamp that lists nothing passes every comparison it makes. Silence is
# "unchecked", not "safe", and the two must not look alike (#2248). Named
# rather than counted, so a duplicate cannot stand in for a missing one.
missing=""
[ "$seen_parser" -eq 1 ] || missing="$missing integrations/treesitter-vibe/src/parser.c"
[ "$seen_play" -eq 1 ] || missing="$missing playground/public/tree-sitter-vibe.wasm"
[ "$seen_zed" -eq 1 ] || missing="$missing integrations/zed-vibe/grammars/vibe.wasm"
if [ -n "$missing" ]; then
  fail "$STAMP does not stamp:$missing
  All three must be listed, or the pairing this gate exists to enforce is not
  enforced for the one that is absent."
fi

echo "[treesitter-artifacts] ok: ABI $abi, all 3 stamped artifacts match"
