#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';

const opcodesPath = 'vibe/builtin/wasm/opcodes.vibe';
const outPath = 'src/core/wasm_intrinsics.mbt';

const opcodesSrc = readFileSync(opcodesPath, 'utf8');
const exportRe = /^export let\s+([a-z0-9_]+)\s*=\s*\(/gm;
const legacyNames = new Set();
for (let m = exportRe.exec(opcodesSrc); m; m = exportRe.exec(opcodesSrc)) {
  legacyNames.add(m[1]);
}

const extraLegacyNames = [
  'i32_shr_u',
  'i32_load',
  'i32_load8_u',
  'i32_store',
  'i32_store8',
  'f32_load',
  'f64_load',
  'f32_store',
  'f64_store',
  'f32_neg',
  'f64_neg',
  'anyref_eq',
  'eqref_eq',
  'i31ref_eq',
  'structref_eq',
  'arrayref_eq',
  'funcref_eq',
  'externref_eq',
];
for (const name of extraLegacyNames) {
  legacyNames.add(name);
}

const typePrefixes = [
  'i32',
  'f32',
  'f64',
  'anyref',
  'eqref',
  'i31ref',
  'structref',
  'arrayref',
  'funcref',
  'externref',
];

function legacyToCanonical(legacy) {
  for (const prefix of typePrefixes) {
    const head = `${prefix}_`;
    if (legacy.startsWith(head) && legacy.length > head.length) {
      const op = legacy.slice(head.length);
      return `%${prefix}.${op}`;
    }
  }
  return null;
}

const canonicalToLegacy = new Map();
for (const legacy of legacyNames) {
  const canonical = legacyToCanonical(legacy);
  if (canonical) {
    canonicalToLegacy.set(canonical, legacy);
  }
}

const lowerOverrides = {
  i32_add: '__add',
  i32_sub: '__sub',
  i32_mul: '__mul',
  i32_div_s: '__div',
  i32_rem_s: '__mod',
  i32_and: '__bit_and',
  i32_or: '__bit_or',
  i32_xor: '__bit_xor',
  i32_shl: '__lshift',
  i32_shr_s: '__rshift',
  f32_add: '__add',
  f32_sub: '__sub',
  f32_mul: '__mul',
  f32_div: '__div',
  f64_add: '__add',
  f64_sub: '__sub',
  f64_mul: '__mul',
  f64_div: '__div',
};

const canonicalList = [...canonicalToLegacy.keys()].sort();
const aliasToCanonical = new Map();
for (const canonical of canonicalList) {
  const legacy = canonicalToLegacy.get(canonical);
  const dot = canonical.indexOf('.');
  const type = canonical.slice(1, dot);
  const op = canonical.slice(dot + 1);
  const aliases = [canonical, `${type}::${op}`, `vibe/wasm/${type}::${op}`];
  for (const alias of aliases) {
    aliasToCanonical.set(alias, canonical);
  }
}

const sortedAliasEntries = [...aliasToCanonical.entries()].sort((a, b) => {
  if (a[1] === b[1]) {
    return a[0].localeCompare(b[0]);
  }
  return a[1].localeCompare(b[1]);
});

const canonicalToLower = new Map();
for (const canonical of canonicalList) {
  const legacy = canonicalToLegacy.get(canonical);
  canonicalToLower.set(canonical, lowerOverrides[legacy] ?? legacy);
}

const wasmReservedTypes = ['i32', 'f32', 'f64'];
const wasmGcRefTypes = [
  'anyref',
  'eqref',
  'i31ref',
  'structref',
  'arrayref',
  'funcref',
  'externref',
];

const out = [];
out.push('///|');
out.push('/// Auto-generated by scripts/gen_wasm_intrinsics_table.mjs.');
out.push('/// DO NOT EDIT MANUALLY.');
out.push('');
out.push('///|');
out.push('pub fn is_wasm_gc_ref_type_name(name : String) -> Bool {');
out.push('  match name {');
out.push(
  `    ${wasmGcRefTypes.map((name) => `"${name}"`).join(' | ')} => true`,
);
out.push('    _ => false');
out.push('  }');
out.push('}');
out.push('');
out.push('///|');
out.push('pub fn is_wasm_reserved_type_name(name : String) -> Bool {');
out.push('  match name {');
out.push(
  `    ${[...wasmReservedTypes, ...wasmGcRefTypes].map((name) => `"${name}"`).join(' | ')} => true`,
);
out.push('    _ => false');
out.push('  }');
out.push('}');
out.push('');
out.push('///|');
out.push('pub fn normalize_wasm_intrinsic_name(name : String) -> String? {');
out.push('  match name {');
let currentCanonical = null;
for (const [alias, canonical] of sortedAliasEntries) {
  if (canonical !== currentCanonical) {
    currentCanonical = canonical;
    out.push(`    "${alias}" => Some("${canonical}")`);
  } else {
    const last = out[out.length - 1];
    out[out.length - 1] = last.replace(' => Some', ` | "${alias}" => Some`);
  }
}
out.push('    _ => None');
out.push('  }');
out.push('}');
out.push('');
out.push('///|');
out.push('pub fn lower_wasm_intrinsic_name(name : String) -> String {');
out.push('  match normalize_wasm_intrinsic_name(name) {');
out.push('    Some(canonical) =>');
out.push('      match canonical {');
for (const canonical of canonicalList) {
  const lowered = canonicalToLower.get(canonical);
  out.push(`        "${canonical}" => "${lowered}"`);
}
out.push('        _ => name');
out.push('      }');
out.push('    None => name');
out.push('  }');
out.push('}');
out.push('');
out.push('///|');
out.push('pub fn wasm_gc_ref_eq_type_name(name : String) -> String? {');
out.push('  match lower_wasm_intrinsic_name(name) {');
for (const t of wasmGcRefTypes) {
  out.push(`    "${t}_eq" => Some("${t}")`);
}
out.push('    _ => None');
out.push('  }');
out.push('}');
out.push('');

writeFileSync(outPath, `${out.join('\n')}\n`);
