#!/usr/bin/env bash
# #820 sub-item 3: emit the vibe "context pack" -- the language cheatsheet
# plus the verified golden-example corpus, bundled into one file for AI
# harnesses to load as context (docs/pl-survey-2026-07.md's finding that
# machine-readable diagnostics + a verified positive-example corpus drive
# generation quality for low-resource languages).
#
# Usage: gen_context_pack.sh <repo_root>   (writes to stdout)
#
# Two callers:
#   - install/install.sh runs this ONCE at install time and ships the
#     output as $TC_DIR/lib/context-pack.md (the source docs/eval tree
#     itself is not shipped with the installed toolchain).
#   - runtime/vibe's `context-pack` case falls back to running this
#     live against a dev checkout when no pre-built asset is found.
#
# Deterministic: no timestamps, no environment-dependent paths in the
# output, so `diff <(gen_context_pack.sh X) <(gen_context_pack.sh X)` is
# always empty and the installed asset can be regenerated and diffed in CI.
set -euo pipefail

ROOT="${1:?usage: gen_context_pack.sh <repo_root>}"
SHEET="$ROOT/docs/cheatsheet.md"
GOLDEN="$ROOT/eval/lang-review/golden"

[ -f "$SHEET" ] || { echo "gen_context_pack: not found: $SHEET" >&2; exit 1; }
[ -d "$GOLDEN" ] || { echo "gen_context_pack: not found: $GOLDEN" >&2; exit 1; }

echo "<!-- vibe context pack: language reference (docs/cheatsheet.md) +"
echo "     verified golden examples (eval/lang-review/golden). Generated by"
echo "     scripts/gen_context_pack.sh -- do not hand-edit. -->"
echo
cat "$SHEET"
echo
echo "## Verified examples (eval/lang-review/golden)"
echo
echo "Each example below compiled and ran against the current compiler with"
echo "the shown output -- these are not illustrative snippets, they are"
echo "executable and verified."

shopt -s nullglob
for f in "$GOLDEN"/*.vibe; do
  base="$(basename "$f" .vibe)"
  exp="$GOLDEN/$base.expected"
  echo
  echo "### $base"
  echo
  echo '```vibe'
  cat "$f"
  echo '```'
  if [ -f "$exp" ]; then
    echo
    echo "Expected output:"
    echo '```'
    cat "$exp"
    echo '```'
  fi
done
