#!/usr/bin/env bash
# Generate selfhost_sources_bundle.vibe — all compiler source files as string constants.
# This allows the selfhost WASM to compile itself without filesystem access.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="${VIBE_SELFHOST_PROJECT_ROOT:-$(dirname "$SCRIPT_DIR")}"
COMPILER_DIR="${VIBE_SELFHOST_COMPILER_DIR:-$PROJECT_ROOT/vibe/compiler}"
MANIFEST="${VIBE_SELFHOST_SOURCE_MANIFEST:-$COMPILER_DIR/selfhost_sources_manifest.tsv}"
OUT="${VIBE_SELFHOST_BUNDLE_OUT:-$COMPILER_DIR/selfhost_sources_bundle.vibe}"

if [ ! -f "$MANIFEST" ]; then
  echo "error: manifest not found: $MANIFEST" >&2
  exit 1
fi

FILES=()
while IFS=$'\t' read -r group relpath; do
  if [ -z "${group}${relpath}" ]; then
    continue
  fi
  case "$group" in
    \#*) continue ;;
  esac
  if [ -z "${relpath:-}" ]; then
    echo "error: invalid manifest row in $MANIFEST: missing path for group '$group'" >&2
    exit 1
  fi
  FILES+=("$relpath")
done < "$MANIFEST"

if [ "${#FILES[@]}" -eq 0 ]; then
  echo "error: manifest contains no compiler sources: $MANIFEST" >&2
  exit 1
fi

{
  echo "// AUTO-GENERATED by scripts/generate_selfhost_bundle.sh"
  echo "// Do not edit manually. Regenerate with: bash scripts/generate_selfhost_bundle.sh"
  echo ""
  echo "//# Selfhost source bundle"
  echo ""
  echo "// All compiler source files bundled as (path, source) pairs."
  echo "// Used by selfbuild_compile_stage2 to avoid filesystem access."
  echo "export let selfhost_sources = () -> Array[(String, String)] {"
  echo "  let sources = Array::slice([(\"\", \"\")], 0, 0)"
  echo ""

  idx=0
  for f in "${FILES[@]}"; do
    filepath="$COMPILER_DIR/$f"
    if [ ! -f "$filepath" ]; then
      echo "error: file not found: $filepath" >&2
      exit 1
    fi
    relpath="vibe/compiler/$f"
    echo "  let source_$idx = (\"$relpath\","
    # Escape the source code for embedding in a vibe string literal
    # Need to escape: backslash -> \\, double quote -> \", newline -> \n
    python3 -c "
import sys
with open('$filepath', 'r') as f:
    content = f.read()
# Escape for vibe string literal
content = content.replace('\\\\', '\\\\\\\\')
content = content.replace('\"', '\\\\\"')
content = content.replace('\n', '\\\\n')
sys.stdout.write('\"' + content + '\"')
"
    echo ")"
    echo "  Array::push(sources, source_$idx)"
    echo ""
    idx=$((idx + 1))
  done

  echo "  sources"
  echo "}"
} > "$OUT"

echo "Generated $OUT ($(wc -l < "$OUT") lines, $(wc -c < "$OUT" | tr -d ' ') bytes)"
