#!/usr/bin/env bash
# Generate selfhost_sources_bundle.vibe — all compiler source files as string constants.
# This allows the selfhost WASM to compile itself without filesystem access.
set -euo pipefail
: "${VIBE_RC:=0}"; export VIBE_RC  # cutover: pin the compiler self-build / gate baseline to bump (RC only when explicitly VIBE_RC=1)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SCRIPT_PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
PROJECT_ROOT="${VIBE_SELFHOST_PROJECT_ROOT:-$(dirname "$SCRIPT_DIR")}"
COMPILER_DIR="${VIBE_SELFHOST_COMPILER_DIR:-$PROJECT_ROOT/vibe/compiler}"
MANIFEST="${VIBE_SELFHOST_SOURCE_MANIFEST:-$COMPILER_DIR/selfhost_sources_manifest.tsv}"
OUT="${VIBE_SELFHOST_BUNDLE_OUT:-$COMPILER_DIR/selfhost_sources_bundle.vibe}"
OUT_ADAPTER="${VIBE_SELFHOST_ADAPTER_BUNDLE_OUT:-$COMPILER_DIR/selfhost_cli_adapter_bundle.vibe}"
OUT_RUNTIME_ENTRY="${VIBE_SELFHOST_RUNTIME_ENTRY_BUNDLE_OUT:-$COMPILER_DIR/selfbuild_runtime_entry_bundle.vibe}"
ADAPTER_MODULE_SOURCE_OUT="${VIBE_SELFHOST_ADAPTER_MODULE_SOURCE_OUT:-}"

if [ ! -f "$MANIFEST" ]; then
  echo "error: manifest not found: $MANIFEST" >&2
  exit 1
fi

MANIFEST_GROUPS=()
FILES=()
while IFS=$'\t' read -r group relpath; do
  if [ -z "${group}${relpath}" ]; then
    continue
  fi
  case "$group" in
    \#*) continue ;;
  esac
  if [ -z "${relpath:-}" ]; then
    echo "error: invalid manifest row in $MANIFEST: missing path for group '$group'" >&2
    exit 1
  fi
  MANIFEST_GROUPS+=("$group")
  FILES+=("$relpath")
done < "$MANIFEST"

# #630: codegen fingerprint. Hash every compiler source file in the manifest
# (excluding generated bundles and the fingerprint file itself) and write it into
# cache/selfhost_codegen_fingerprint.vibe. persistent_cache folds this into the
# artifact cache key, so any change to codegen source invalidates stale compiled
# `.hex` artifacts even when the USER source is unchanged. Deterministic (manifest
# order); independent of its own output, so regeneration is stable.
CODEGEN_FP_FILE="$COMPILER_DIR/cache/selfhost_codegen_fingerprint.vibe"
# Portable sha256 over stdin (macOS install-smoke has no `sha256sum`, only
# `shasum`). Both print the hash first, so `cut -c1-16` yields the same 16 hex
# chars on either — the fingerprint value is unchanged.
sha256_stdin() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum
  else
    shasum -a 256
  fi
}
# Concatenate the codegen source files (excluding generated/self outputs). Kept a
# top-level function rather than inline in the `$(...)` below: bash 3.2 (macOS
# default) mis-parses a `case` nested in command substitution ("syntax error near
# unexpected token `newline'"), which broke the install-smoke generation step.
collect_codegen_sources() {
  local relpath f
  for relpath in "${FILES[@]}"; do
    case "$relpath" in
      *_bundle.vibe|*module_source*|cache/selfhost_codegen_fingerprint.vibe) continue ;;
    esac
    f="$COMPILER_DIR/$relpath"
    [ -f "$f" ] && cat "$f"
  done
}
codegen_fp="$(collect_codegen_sources | sha256_stdin | cut -c1-16)"
cat > "$CODEGEN_FP_FILE" <<FPEOF
// AUTO-GENERATED by scripts/generate_selfhost_bundle.sh (#630).
// Do not edit manually. Regenerate with: bash scripts/generate_selfhost_bundle.sh
//
// A hash of every compiler source file in selfhost_sources_manifest.tsv (the
// codegen included). persistent_cache folds it into the artifact cache key so a
// codegen change — which produces different wasm from the SAME user source —
// automatically invalidates stale compiled .hex artifacts (#630).

//# Functions

export let selfhost_codegen_fingerprint: () -> String = () -> {
  "$codegen_fp"
}
FPEOF

cli_adapter_index_rows_file="$(mktemp)"
# Reachability analysis: adapter entry + GC backend as additional entry
# Outputs:
#   reachable\t<idx>        — files reachable from adapter entry
#   ordered\t<idx>          — dependency-ordered files from adapter entry
#   bundle_reachable\t<idx> — files reachable from adapter entry + GC backend (for main bundle)
python3 - "$COMPILER_DIR" "$MANIFEST" "selfhost_cli_adapter.vibe" >"$cli_adapter_index_rows_file" <<'PY'
import os
import re
import sys

compiler_dir, manifest_path, root_rel = sys.argv[1:]
rows = []
for raw in open(manifest_path, "r", encoding="utf-8"):
    line = raw.rstrip("\n")
    if not line or line.startswith("#"):
        continue
    parts = line.split("\t")
    if len(parts) != 2:
        continue
    rows.append((parts[0], parts[1]))

source_by_rel = {}
for _, rel in rows:
    full = os.path.join(compiler_dir, rel)
    if os.path.isfile(full):
        with open(full, "r", encoding="utf-8") as f:
            source_by_rel[rel] = f.read()

dep_pattern = re.compile(r'^\s*(?:import|export)\s+(\.[\w./\s-]+?)(?:\.vibe)?\s*\{', re.MULTILINE)

def normalize_path(path: str) -> str:
    parts = []
    for seg in path.split("/"):
        if seg == "" or seg == ".":
            continue
        if seg == "..":
            if parts:
                parts.pop()
            continue
        parts.append(seg)
    return "/".join(parts)

def resolve_path(base_rel: str, raw_path: str) -> str:
    base_dir = os.path.dirname(base_rel)
    raw_path = re.sub(r'\s*/\s*', '/', raw_path.strip())
    path = raw_path if raw_path.endswith(".vibe") else raw_path + ".vibe"
    if path.startswith("./") or path.startswith("../"):
        if base_dir:
            candidate = normalize_path(base_dir + "/" + path)
        else:
            candidate = normalize_path(path)
    else:
        candidate = normalize_path(path)
    if candidate in source_by_rel:
        return candidate
    # Try index.vibe fallback for directory-style imports
    idx_candidate = candidate.replace(".vibe", "/index.vibe")
    if idx_candidate in source_by_rel:
        return idx_candidate
    return candidate

reachable = set()

def visit(rel: str):
    if rel in reachable:
        return
    source = source_by_rel.get(rel)
    if source is None:
        return
    reachable.add(rel)
    for dep in dep_pattern.findall(source):
        visit(resolve_path(rel, dep))

visit(root_rel)
index_by_rel = {}
for pair_index, (_, rel) in enumerate(rows):
    index_by_rel[rel] = pair_index
for idx, (_, rel) in enumerate(rows):
    if rel in reachable:
        print("reachable\t" + str(idx))

visited = set()
ordered = []

def visit_ordered(rel: str):
    if rel in visited:
        return
    source = source_by_rel.get(rel)
    if source is None:
        return
    visited.add(rel)
    for dep in dep_pattern.findall(source):
        visit_ordered(resolve_path(rel, dep))
    ordered.append(rel)

visit_ordered(root_rel)
for rel in ordered:
    idx = index_by_rel.get(rel)
    if idx is not None:
        print("ordered\t" + str(idx))

# Bundle reachability: adapter entry + GC backend
bundle_reachable = set(reachable)

def visit_bundle(rel: str):
    if rel in bundle_reachable:
        return
    source = source_by_rel.get(rel)
    if source is None:
        return
    bundle_reachable.add(rel)
    for dep in dep_pattern.findall(source):
        visit_bundle(resolve_path(rel, dep))

# Additional entry points for the main bundle
bundle_extra_entries = os.environ.get("VIBE_SELFHOST_BUNDLE_EXTRA_ENTRIES", "codegen/gc/index.vibe,index.vibe")
for entry in bundle_extra_entries.split(","):
    entry = entry.strip()
    if entry:
        visit_bundle(entry)

for idx, (_, rel) in enumerate(rows):
    if rel in bundle_reachable:
        print("bundle_reachable\t" + str(idx))
PY
CLI_ADAPTER_INDEXES=()
CLI_ADAPTER_ORDERED_INDEXES=()
BUNDLE_REACHABLE_INDEXES=()
while IFS=$'\t' read -r kind idx; do
  if [ -z "${kind}${idx}" ]; then
    continue
  fi
  if [ "$kind" = "reachable" ]; then
    CLI_ADAPTER_INDEXES+=("$idx")
  elif [ "$kind" = "ordered" ]; then
    CLI_ADAPTER_ORDERED_INDEXES+=("$idx")
  elif [ "$kind" = "bundle_reachable" ]; then
    BUNDLE_REACHABLE_INDEXES+=("$idx")
  fi
done < "$cli_adapter_index_rows_file"
rm -f "$cli_adapter_index_rows_file"

main_index_rows_file="$(mktemp)"
python3 - "$COMPILER_DIR" "$MANIFEST" "index.vibe" >"$main_index_rows_file" <<'PY'
import os
import re
import sys

compiler_dir, manifest_path, root_rel = sys.argv[1:]
rows = []
for raw in open(manifest_path, "r", encoding="utf-8"):
    line = raw.rstrip("\n")
    if not line or line.startswith("#"):
        continue
    parts = line.split("\t")
    if len(parts) != 2:
        continue
    rows.append((parts[0], parts[1]))

source_by_rel = {}
for _, rel in rows:
    full = os.path.join(compiler_dir, rel)
    if os.path.isfile(full):
        with open(full, "r", encoding="utf-8") as f:
            source_by_rel[rel] = f.read()

dep_pattern = re.compile(r'^\s*(?:import|export)\s+(\.[\w./\s-]+?)(?:\.vibe)?\s*\{', re.MULTILINE)

def normalize_path(path: str) -> str:
    parts = []
    for seg in path.split("/"):
        if seg == "" or seg == ".":
            continue
        if seg == "..":
            if parts:
                parts.pop()
            continue
        parts.append(seg)
    return "/".join(parts)

def resolve_path(base_rel: str, raw_path: str) -> str:
    base_dir = os.path.dirname(base_rel)
    raw_path = re.sub(r'\s*/\s*', '/', raw_path.strip())
    path = raw_path if raw_path.endswith(".vibe") else raw_path + ".vibe"
    if path.startswith("./") or path.startswith("../"):
        if base_dir:
            candidate = normalize_path(base_dir + "/" + path)
        else:
            candidate = normalize_path(path)
    else:
        candidate = normalize_path(path)
    if candidate in source_by_rel:
        return candidate
    idx_candidate = candidate.replace(".vibe", "/index.vibe")
    if idx_candidate in source_by_rel:
        return idx_candidate
    return candidate

index_by_rel = {}
for pair_index, (_, rel) in enumerate(rows):
    index_by_rel[rel] = pair_index

visited = set()
ordered = []

def visit_ordered(rel: str):
    if rel in visited:
        return
    source = source_by_rel.get(rel)
    if source is None:
        return
    visited.add(rel)
    for dep in dep_pattern.findall(source):
        visit_ordered(resolve_path(rel, dep))
    ordered.append(rel)

visit_ordered(root_rel)
for rel in ordered:
    idx = index_by_rel.get(rel)
    if idx is not None:
        print(idx)
PY
MAIN_ORDERED_INDEXES=()
while IFS= read -r idx; do
  if [ -n "${idx}" ]; then
    MAIN_ORDERED_INDEXES+=("$idx")
  fi
done < "$main_index_rows_file"
rm -f "$main_index_rows_file"

# Build lookup set for bundle reachability filter
is_bundle_reachable() {
  local target="$1"
  local idx
  for idx in "${BUNDLE_REACHABLE_INDEXES[@]}"; do
    if [ "$idx" = "$target" ]; then
      return 0
    fi
  done
  return 1
}

if [ "${#FILES[@]}" -eq 0 ]; then
  echo "error: manifest contains no compiler sources: $MANIFEST" >&2
  exit 1
fi

find_adapter_local_index() {
  local target="$1"
  local i=0
  local idx
  for idx in "${CLI_ADAPTER_INDEXES[@]}"; do
    if [ "$idx" = "$target" ]; then
      echo "$i"
      return 0
    fi
    i=$((i + 1))
  done
  return 1
}

find_bundle_local_index() {
  local target="$1"
  local pair manifest_idx local_idx
  for pair in "${BUNDLE_SOURCE_INDEXES[@]}"; do
    manifest_idx="${pair%%:*}"
    local_idx="${pair#*:}"
    if [ "$manifest_idx" = "$target" ]; then
      echo "$local_idx"
      return 0
    fi
  done
  return 1
}

is_main_ordered() {
  local target="$1"
  local idx
  for idx in "${MAIN_ORDERED_INDEXES[@]}"; do
    if [ "$idx" = "$target" ]; then
      return 0
    fi
  done
  return 1
}

write_vibe_string_literal_from_file() {
  local filepath="$1"
  python3 - "$filepath" <<'PY'
import sys

with open(sys.argv[1], "r", encoding="utf-8") as f:
    content = f.read()
content = content.replace("\\", "\\\\")
content = content.replace('"', '\\"')
content = content.replace("\n", "\\n")
sys.stdout.write('"' + content + '"')
PY
}

write_vibe_chunked_string_function_from_file() {
  local prefix="$1"
  local export_name="$2"
  local filepath="${3:-}"
  local chunk_size="${VIBE_SELFHOST_BUNDLE_CHUNK_SIZE:-8192}"
  if [ -z "$filepath" ] || [ ! -f "$filepath" ]; then
    echo "export let $export_name = () -> String {"
    echo "  \"\""
    echo "}"
    return 0
  fi
  python3 - "$filepath" "$prefix" "$export_name" "$chunk_size" <<'PY'
import sys

filepath, prefix, export_name, chunk_size = sys.argv[1:]
chunk_size = int(chunk_size)
with open(filepath, "r", encoding="utf-8") as f:
    content = f.read()

def esc(text: str) -> str:
    text = text.replace("\\", "\\\\")
    text = text.replace('"', '\\"')
    text = text.replace("\n", "\\n")
    return text

chunks = [content[i:i + chunk_size] for i in range(0, len(content), chunk_size)]
if not chunks:
    chunks = [""]

print(f"export let {export_name} = () -> String {{")
if len(chunks) == 1:
    print(f'  "{esc(chunks[0])}"')
else:
    print("  let sb = StringBuilder::new()")
    for chunk in chunks:
        print(f'  StringBuilder::push(sb, "{esc(chunk)}")')
    print("  StringBuilder::freeze(sb)")
print("}")
PY
}

write_vibe_string_function_from_file() {
  local binding_name="$1"
  local export_name="$2"
  local filepath="${3:-}"
  if [ -z "$filepath" ] || [ ! -f "$filepath" ]; then
    echo "export let $export_name = () -> String {"
    echo "  \"\""
    echo "}"
    return 0
  fi
  echo "export let $export_name = () -> String {"
  printf '  '
  write_vibe_string_literal_from_file "$filepath"
  echo ""
  echo "}"
}

run_host_vibe_cmd() {
  local cmd="$1"
  shift
  local release_vibe="$SCRIPT_PROJECT_ROOT/_build/native/release/build/cmd/vibe/vibe.exe"
  local debug_vibe="$SCRIPT_PROJECT_ROOT/_build/native/debug/build/cmd/vibe/vibe.exe"
  if [ "$cmd" = "emit-module-source" ]; then
    # #594 Stage 1b/seed-bump: prefer the selfhost seed compiler (moon-free).
    # The seed carries emit-module-source (VIBE_EMIT_MODULE_SOURCE mode), so the
    # flat module source needs no MoonBit host. Args are (input, output, entry),
    # rewritten to repo-root-relative for the wasm preopen. Force the legacy host
    # path with VIBE_SELFHOST_EMIT_VIA_HOST=1.
    local seed_wasm="$SCRIPT_PROJECT_ROOT/bootstrap/selfhost/seed/selfhost_compiler.wasm"
    if [ -f "$seed_wasm" ] && [ "${VIBE_SELFHOST_EMIT_VIA_HOST:-0}" != "1" ]; then
      local emit_in="${1#"$SCRIPT_PROJECT_ROOT"/}"
      local emit_out="${2#"$SCRIPT_PROJECT_ROOT"/}"
      local emit_entry="${3:-cli_main}"
      (
        cd "$SCRIPT_PROJECT_ROOT" &&
          VIBE_PREOPEN_DIR="$SCRIPT_PROJECT_ROOT" \
            VIBE_EMIT_MODULE_SOURCE=1 \
            VIBE_SELFHOST_IMPORT_ABI="${VIBE_SELFHOST_IMPORT_ABI:-raw}" \
            bash "$SCRIPT_PROJECT_ROOT/scripts/run_wasm_vibe_host_runner.sh" \
            --invoke cli_main "$seed_wasm" "$emit_in" "$emit_out" "$emit_entry"
      )
      return 0
    fi
    if [ -x "$release_vibe" ]; then
      (cd "$SCRIPT_PROJECT_ROOT" && "$release_vibe" "$cmd" "$@")
      return 0
    fi
    if [ -x "$debug_vibe" ]; then
      (cd "$SCRIPT_PROJECT_ROOT" && "$debug_vibe" "$cmd" "$@")
      return 0
    fi
    (cd "$SCRIPT_PROJECT_ROOT" && moon build --target native --release src/cmd/vibe --warn-list '-1-7-24-29' >/dev/null)
    "$release_vibe" "$cmd" "$@"
    return 0
  fi
  if [ -x "$release_vibe" ]; then
    (cd "$SCRIPT_PROJECT_ROOT" && "$release_vibe" "$cmd" "$@")
    return 0
  fi
  if [ -x "$debug_vibe" ]; then
    (cd "$SCRIPT_PROJECT_ROOT" && "$debug_vibe" "$cmd" "$@")
    return 0
  fi
  (cd "$SCRIPT_PROJECT_ROOT" && moon run --target native src/cmd/vibe -- "$cmd" "$@")
}

build_adapter_module_source() {
  local merged_source_file="$1"
  # Fast path for tiny shell self-tests; production generation uses
  # emit-module-source through the host compiler below.
  if [ "${VIBE_SELFHOST_ADAPTER_MODULE_SOURCE_FROM_MERGED:-0}" = "1" ]; then
    local module_source_path
    mkdir -p "$PROJECT_ROOT/_build"
    module_source_path="$(mktemp "$PROJECT_ROOT/_build/selfhost_cli_adapter_module_source.XXXXXX")"
    python3 - "$merged_source_file" "$module_source_path" <<'PY'
import sys

src, out = sys.argv[1:]
with open(src, "r", encoding="utf-8") as f:
    lines = f.readlines()

with open(out, "w", encoding="utf-8") as f:
    for line in lines:
        stripped = line.lstrip()
        if stripped.startswith("let ") and "->" not in stripped:
            continue
        f.write(line)
PY
    printf '%s\n' "$module_source_path"
    return 0
  fi
  # Moon-free default (#594 Stage 1): prefer the committed prebuilt flat
  # module source so that seed -> stage1 -> stage2 needs no MoonBit host.
  # emit-module-source is a deterministic function of the compiler source;
  # the committed copy is kept fresh by scripts/check_selfhost_module_source_sync.sh
  # (run in selfhost-gate). Force regeneration through the host compiler with
  # VIBE_SELFHOST_REGEN_MODULE_SOURCE=1 (used by that gate and by intentional
  # module-source bumps).
  local committed_module_source="$COMPILER_DIR/selfhost_cli_adapter_module_source.vibe"
  if [ "${VIBE_SELFHOST_REGEN_MODULE_SOURCE:-0}" != "1" ] && [ -s "$committed_module_source" ]; then
    local module_source_path
    mkdir -p "$PROJECT_ROOT/_build"
    module_source_path="$(mktemp "$PROJECT_ROOT/_build/selfhost_cli_adapter_module_source.XXXXXX")"
    cp "$committed_module_source" "$module_source_path"
    printf '%s\n' "$module_source_path"
    return 0
  fi
  local module_source_path
  mkdir -p "$PROJECT_ROOT/_build"
  module_source_path="$(mktemp "$PROJECT_ROOT/_build/selfhost_cli_adapter_module_source.XXXXXX")"
  run_host_vibe_cmd emit-module-source "$merged_source_file" "$module_source_path" "cli_main" >/dev/null
  printf '%s\n' "$module_source_path"
}

write_adapter_bundle() {
  local merged_source_file="${1:-}"
  local module_source_file="${2:-}"
  {
  echo "// AUTO-GENERATED by scripts/generate_selfhost_bundle.sh"
  echo "// Do not edit manually. Regenerate with: bash scripts/generate_selfhost_bundle.sh"
  echo ""
  echo "//# Selfhost CLI adapter bundle"
  echo ""
  echo "let cli_adapter_empty_grouped_sources = () -> Array[(String, Array[(String, String)])] {"
  echo "  Array::slice([(\"\", Array::slice([(\"\", \"\")], 0, 0))], 0, 0)"
  echo "}"
  echo ""
  echo "let cli_adapter_push_grouped_source_pair = (groups: Array[(String, Array[(String, String)])], group_name: String, pair: (String, String)) -> Unit {"
  echo "  let (path, source) = pair"
  echo "  let mut i = 0"
  echo "  let mut found = false"
  echo "  while i < Array::length(groups) {"
  echo "    let (name, sources) = Array::get(groups, i)"
  echo "    if String::equals(name, group_name) {"
  echo "      Array::push(sources, (path, source))"
  echo "      found = true"
  echo "      i = Array::length(groups)"
  echo "    } else {"
  echo "      i = i + 1"
  echo "    }"
  echo "  }"
  echo "  if !found {"
  echo "    let sources = Array::slice([(\"\", \"\")], 0, 0)"
  echo "    Array::push(sources, (path, source))"
  echo "    Array::push(groups, (group_name, sources))"
  echo "  }"
  echo "}"
  echo ""

  adapter_local_idx=0
  for idx in "${CLI_ADAPTER_INDEXES[@]}"; do
    f="${FILES[$idx]}"
    filepath="$COMPILER_DIR/$f"
    relpath="vibe/compiler/$f"
    echo "let cli_adapter_source_$adapter_local_idx = () -> (String, String) {"
    echo "  (\"$relpath\","
    write_vibe_string_literal_from_file "$filepath"
    echo ")"
    echo "}"
    echo ""
    adapter_local_idx=$((adapter_local_idx + 1))
  done

  echo "export let selfhost_cli_adapter_sources = () -> Array[(String, String)] {"
  echo "  let sources = Array::slice([(\"\", \"\")], 0, 0)"
  adapter_local_idx=0
  for _idx in "${CLI_ADAPTER_INDEXES[@]}"; do
    echo "  Array::push(sources, cli_adapter_source_$adapter_local_idx())"
    adapter_local_idx=$((adapter_local_idx + 1))
  done
  echo "  sources"
  echo "}"
  echo ""
  echo "export let selfhost_cli_adapter_source_groups = () -> Array[(String, Array[(String, String)])] {"
  echo "  let groups = cli_adapter_empty_grouped_sources()"
  adapter_local_idx=0
  for idx in "${CLI_ADAPTER_INDEXES[@]}"; do
    group="${MANIFEST_GROUPS[$idx]}"
    echo "  cli_adapter_push_grouped_source_pair(groups, \"$group\", cli_adapter_source_$adapter_local_idx())"
    adapter_local_idx=$((adapter_local_idx + 1))
  done
  echo "  groups"
  echo "}"
  echo ""
  echo "export let selfhost_cli_adapter_ordered_sources = () -> Array[(String, String)] {"
  echo "  let sources = Array::slice([(\"\", \"\")], 0, 0)"
  for idx in "${CLI_ADAPTER_ORDERED_INDEXES[@]}"; do
    adapter_local_idx="$(find_adapter_local_index "$idx")"
    echo "  Array::push(sources, cli_adapter_source_$adapter_local_idx())"
  done
  echo "  sources"
  echo "}"
  echo ""
  write_vibe_string_function_from_file \
    "selfhost_cli_adapter_merged_source_value" \
    "selfhost_cli_adapter_merged_source" \
    "$merged_source_file"
  echo ""
  write_vibe_string_function_from_file \
    "selfhost_cli_adapter_module_source_value" \
    "selfhost_cli_adapter_module_source" \
    "$module_source_file"
  } > "$OUT_ADAPTER"
}

write_runtime_entry_bundle() {
  {
  echo "// AUTO-GENERATED by scripts/generate_selfhost_bundle.sh"
  echo "// Do not edit manually. Regenerate with: bash scripts/generate_selfhost_bundle.sh"
  echo ""
  echo "//# Selfbuild runtime entry bundle"
  echo ""
  write_vibe_chunked_string_function_from_file \
    "selfbuild_runtime_entry_source" \
    "selfbuild_runtime_entry_source" \
    "$COMPILER_DIR/selfbuild_runtime_entry.vibe"
  } > "$OUT_RUNTIME_ENTRY"
}

build_exact_adapter_merged_source() {
  # #726: flatten via the compiler's OWN merge machinery (ExportRenamePlan +
  # private namespacing), replacing the Python flattener. The emit tool
  # (vibe/compiler/emit_merged_source_entry.vibe) is FS-compiled fresh from
  # the current source with the committed seed -- a normal multi-file compile,
  # which itself runs the real merge -- then run to flatten the adapter entry.
  # The old flattener stripped import/export lines and concatenated files,
  # leaving duplicate top-level defs resolved by fn-table first-match; the
  # merge renames them, so the flat source has ZERO duplicates (asserted
  # below) and carries the #716 visibility guarantees.
  local merged_path
  mkdir -p "$PROJECT_ROOT/_build"
  merged_path="$(mktemp "$PROJECT_ROOT/_build/selfhost_cli_adapter_merged_source.XXXXXX")"
  local tool_wasm="$PROJECT_ROOT/_build/emit_merged_source_tool.wasm"
  local seed_wasm="$PROJECT_ROOT/bootstrap/selfhost/seed/selfhost_compiler.wasm"
  rm -f "$tool_wasm" "$tool_wasm.diag"
  (cd "$PROJECT_ROOT" && env VIBE_RC=0 VIBE_PREOPEN_DIR="$PROJECT_ROOT" VIBE_FS_COMPILE=1 \
    VIBE_SELFHOST_IMPORT_ABI="${VIBE_SELFHOST_IMPORT_ABI:-raw}" \
    bash scripts/run_wasm_vibe_host_runner.sh --invoke cli_main "$seed_wasm" \
    vibe/compiler/emit_merged_source_entry.vibe "$tool_wasm" cli_main >/dev/null 2>&1) || true
  if [ ! -s "$tool_wasm" ]; then
    echo "generate_selfhost_bundle: merge-flatten tool build failed" >&2
    cat "$tool_wasm.diag" >&2 2>/dev/null || true
    exit 1
  fi
  rm -f "$merged_path.diag"
  (cd "$PROJECT_ROOT" && VIBE_PREOPEN_DIR="$PROJECT_ROOT" \
    bash scripts/run_wasm_vibe_host_runner.sh --invoke cli_main "$tool_wasm" \
    vibe/compiler/selfhost_cli_adapter.vibe "$merged_path" >/dev/null 2>&1) || true
  if [ ! -s "$merged_path" ]; then
    echo "generate_selfhost_bundle: merge flatten failed" >&2
    cat "$merged_path.diag" >&2 2>/dev/null || true
    exit 1
  fi
  # #726 gate: the merged flat source must have ZERO duplicate top-level defs.
  local dups
  dups="$(grep -E '^(export )?let (rec )?(mut )?[A-Za-z_]' "$merged_path" \
    | sed -E 's/^(export )?let (rec )?(mut )?([A-Za-z_][A-Za-z0-9_:#]*).*/\4/' \
    | sort | uniq -d | wc -l | tr -d ' ')"
  if [ "$dups" != "0" ]; then
    echo "generate_selfhost_bundle: $dups duplicate top-level def(s) in merged source (#726)" >&2
    grep -E '^(export )?let (rec )?(mut )?[A-Za-z_]' "$merged_path" \
      | sed -E 's/^(export )?let (rec )?(mut )?([A-Za-z_][A-Za-z0-9_:#]*).*/\4/' \
      | sort | uniq -d >&2
    exit 1
  fi
  printf '%s\n' "$merged_path"
}

write_adapter_bundle "" ""
ADAPTER_MERGED_SOURCE_FILE="$(build_exact_adapter_merged_source)"
ADAPTER_MODULE_SOURCE_FILE="$(build_adapter_module_source "$ADAPTER_MERGED_SOURCE_FILE")"
if [ -n "$ADAPTER_MODULE_SOURCE_OUT" ]; then
  mkdir -p "$(dirname "$ADAPTER_MODULE_SOURCE_OUT")"
  cp "$ADAPTER_MODULE_SOURCE_FILE" "$ADAPTER_MODULE_SOURCE_OUT"
fi
write_adapter_bundle "$ADAPTER_MERGED_SOURCE_FILE" "$ADAPTER_MODULE_SOURCE_FILE"
write_runtime_entry_bundle

{
  echo "// AUTO-GENERATED by scripts/generate_selfhost_bundle.sh"
  echo "// Do not edit manually. Regenerate with: bash scripts/generate_selfhost_bundle.sh"
  echo ""
  echo "//# Selfhost source bundle"
  echo ""
  echo "// All compiler source files bundled as (path, source) pairs."
  echo "// Used by selfbuild_compile_stage2 to avoid filesystem access."
  echo "let empty_grouped_sources = () -> Array[(String, Array[(String, String)])] {"
  echo "  Array::slice([(\"\", Array::slice([(\"\", \"\")], 0, 0))], 0, 0)"
  echo "}"
  echo ""
  echo "let push_grouped_source_pair = (groups: Array[(String, Array[(String, String)])], group_name: String, pair: (String, String)) -> Unit {"
  echo "  let (path, source) = pair"
  echo "  let mut i = 0"
  echo "  let mut found = false"
  echo "  while i < Array::length(groups) {"
  echo "    let (name, sources) = Array::get(groups, i)"
  echo "    if String::equals(name, group_name) {"
  echo "      Array::push(sources, (path, source))"
  echo "      found = true"
  echo "      i = Array::length(groups)"
  echo "    } else {"
  echo "      i = i + 1"
  echo "    }"
  echo "  }"
  echo "  if !found {"
  echo "    let sources = Array::slice([(\"\", \"\")], 0, 0)"
  echo "    Array::push(sources, (path, source))"
  echo "    Array::push(groups, (group_name, sources))"
  echo "  }"
  echo "}"
  echo ""
  # Only include files reachable from entry points (adapter + GC backend)
  BUNDLE_SOURCE_INDEXES=()
  bundle_local_idx=0
  idx=0
  for f in "${FILES[@]}"; do
    if ! is_bundle_reachable "$idx"; then
      idx=$((idx + 1))
      continue
    fi
    if [ "$f" = "selfhost_cli_adapter_bundle.vibe" ]; then
      filepath="$OUT_ADAPTER"
    elif [ "$f" = "selfbuild_runtime_entry_bundle.vibe" ]; then
      filepath="$OUT_RUNTIME_ENTRY"
    else
      filepath="$COMPILER_DIR/$f"
    fi
    if [ ! -f "$filepath" ]; then
      echo "error: file not found: $filepath" >&2
      exit 1
    fi
    relpath="vibe/compiler/$f"
    echo "let selfhost_source_$bundle_local_idx = () -> (String, String) {"
    echo "  (\"$relpath\","
    # Escape the source code for embedding in a vibe string literal
    # Need to escape: backslash -> \\, double quote -> \", newline -> \n
    python3 -c "
import sys, re
with open('$filepath', 'r') as f:
    content = f.read()
# Strip relative import/export statements (they are resolved by collect_merged_stmts)
drop_pattern = re.compile(r'^\s*(?:import|export)\s+\.[\w./\s-]+')
lines = content.splitlines(True)
out = []
skipping = False
depth = 0
for line in lines:
    stripped = line.lstrip()
    if stripped.startswith('//'): continue
    if not skipping and drop_pattern.match(line):
        depth = line.count('{') - line.count('}')
        if depth > 0: skipping = True
        continue
    if skipping:
        depth += line.count('{') - line.count('}')
        if depth <= 0: skipping = False
        continue
    out.append(line)
content = ''.join(out)
# Escape for vibe string literal
content = content.replace('\\\\', '\\\\\\\\')
content = content.replace('\"', '\\\\\"')
content = content.replace('\n', '\\\\n')
sys.stdout.write('\"' + content + '\"')
"
    echo ")"
    echo "}"
    echo ""
    BUNDLE_SOURCE_INDEXES+=("$idx:$bundle_local_idx")
    bundle_local_idx=$((bundle_local_idx + 1))
    idx=$((idx + 1))
  done

  echo "export let selfhost_sources = () -> Array[(String, String)] {"
  echo "  let sources = Array::slice([(\"\", \"\")], 0, 0)"
  echo ""

  for pair in "${BUNDLE_SOURCE_INDEXES[@]}"; do
    local_idx="${pair#*:}"
    echo "  Array::push(sources, selfhost_source_$local_idx())"
  done

  echo "  sources"
  echo "}"
  echo ""
  echo "export let selfhost_source_groups = () -> Array[(String, Array[(String, String)])] {"
  echo "  let groups = empty_grouped_sources()"
  echo ""

  for pair in "${BUNDLE_SOURCE_INDEXES[@]}"; do
    manifest_idx="${pair%%:*}"
    local_idx="${pair#*:}"
    group="${MANIFEST_GROUPS[$manifest_idx]}"
    echo "  push_grouped_source_pair(groups, \"$group\", selfhost_source_$local_idx())"
  done

  echo ""
  echo "  groups"
  echo "}"
  echo ""
  echo "export let selfhost_ordered_sources = () -> Array[(String, String)] {"
  echo "  let sources = Array::slice([(\"\", \"\")], 0, 0)"
  for idx in "${MAIN_ORDERED_INDEXES[@]}"; do
    if local_idx="$(find_bundle_local_index "$idx")"; then
      echo "  Array::push(sources, selfhost_source_$local_idx())"
    fi
  done
  echo "  sources"
  echo "}"
  echo ""
  echo "export let selfhost_ordered_source_groups = () -> Array[(String, Array[(String, String)])] {"
  echo "  let groups = empty_grouped_sources()"
  for pair in "${BUNDLE_SOURCE_INDEXES[@]}"; do
    manifest_idx="${pair%%:*}"
    local_idx="${pair#*:}"
    if is_main_ordered "$manifest_idx"; then
      group="${MANIFEST_GROUPS[$manifest_idx]}"
      echo "  push_grouped_source_pair(groups, \"$group\", selfhost_source_$local_idx())"
    fi
  done
  echo "  groups"
  echo "}"
} > "$OUT"

echo "Generated $OUT ($(wc -l < "$OUT") lines, $(wc -c < "$OUT" | tr -d ' ') bytes)"
echo "Generated $OUT_ADAPTER ($(wc -l < "$OUT_ADAPTER") lines, $(wc -c < "$OUT_ADAPTER" | tr -d ' ') bytes)"
echo "Generated $OUT_RUNTIME_ENTRY ($(wc -l < "$OUT_RUNTIME_ENTRY") lines, $(wc -c < "$OUT_RUNTIME_ENTRY" | tr -d ' ') bytes)"
