#!/usr/bin/env bash
# Generate compiler_sources_bundle.vibe — all compiler source files as string constants.
# This allows the compiler wasm to compile itself without filesystem access.
set -euo pipefail
: "${VIBE_RC:=0}"; export VIBE_RC  # cutover: pin the compiler self-build / gate baseline to bump (RC only when explicitly VIBE_RC=1)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SCRIPT_PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
PROJECT_ROOT="${VIBE_PROJECT_ROOT:-$(dirname "$SCRIPT_DIR")}"
. "$PROJECT_ROOT/scripts/trace_lib.sh"
COMPILER_DIR="${VIBE_COMPILER_DIR:-$PROJECT_ROOT/lib/@vibe/compiler}"
MANIFEST="${VIBE_SOURCE_MANIFEST:-$COMPILER_DIR/compiler_sources_manifest.tsv}"
OUT="${VIBE_BUNDLE_OUT:-$COMPILER_DIR/compiler_sources_bundle.vibe}"
OUT_ADAPTER="${VIBE_ADAPTER_BUNDLE_OUT:-$COMPILER_DIR/cli_adapter_bundle.vibe}"
OUT_RUNTIME_ENTRY="${VIBE_RUNTIME_ENTRY_BUNDLE_OUT:-$COMPILER_DIR/selfbuild_runtime_entry_bundle.vibe}"
ADAPTER_MODULE_SOURCE_OUT="${VIBE_ADAPTER_MODULE_SOURCE_OUT:-}"

if [ ! -f "$MANIFEST" ]; then
  echo "error: manifest not found: $MANIFEST" >&2
  exit 1
fi

MANIFEST_GROUPS=()
FILES=()
while IFS=$'\t' read -r group relpath; do
  if [ -z "${group}${relpath}" ]; then
    continue
  fi
  case "$group" in
    \#*) continue ;;
  esac
  if [ -z "${relpath:-}" ]; then
    echo "error: invalid manifest row in $MANIFEST: missing path for group '$group'" >&2
    exit 1
  fi
  MANIFEST_GROUPS+=("$group")
  FILES+=("$relpath")
done < "$MANIFEST"

# #630: codegen fingerprint. Hash every compiler source file in the manifest
# (excluding generated bundles and the fingerprint file itself) and write it into
# cache/codegen_fingerprint.vibe. persistent_cache folds this into the
# artifact cache key, so any change to codegen source invalidates stale compiled
# `.hex` artifacts even when the USER source is unchanged. Deterministic (manifest
# order); independent of its own output, so regeneration is stable.
CODEGEN_FP_FILE="$COMPILER_DIR/cache/codegen_fingerprint.vibe"
# Portable sha256 over stdin (macOS install-smoke has no `sha256sum`, only
# `shasum`). Both print the hash first, so `cut -c1-16` yields the same 16 hex
# chars on either — the fingerprint value is unchanged.
sha256_stdin() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum
  else
    shasum -a 256
  fi
}
# Concatenate the codegen source files (excluding generated/self outputs). Kept a
# top-level function rather than inline in the `$(...)` below: bash 3.2 (macOS
# default) mis-parses a `case` nested in command substitution ("syntax error near
# unexpected token `newline'"), which broke the install-smoke generation step.
collect_codegen_sources() {
  local relpath f
  for relpath in "${FILES[@]}"; do
    case "$relpath" in
      *_bundle.vibe|*module_source*|cache/codegen_fingerprint.vibe) continue ;;
    esac
    f="$COMPILER_DIR/$relpath"
    [ -f "$f" ] && cat "$f"
  done
}
codegen_fp="$(collect_codegen_sources | sha256_stdin | cut -c1-16)"
cat > "$CODEGEN_FP_FILE" <<FPEOF
// AUTO-GENERATED by scripts/generate_bundle.sh (#630).
// Do not edit manually. Regenerate with: bash scripts/generate_bundle.sh
//
// A hash of every compiler source file in compiler_sources_manifest.tsv (the
// codegen included). persistent_cache folds it into the artifact cache key so a
// codegen change — which produces different wasm from the SAME user source —
// automatically invalidates stale compiled .hex artifacts (#630).

//# Functions

export let codegen_fingerprint: () -> String = () -> {
  "$codegen_fp"
}
FPEOF

cli_adapter_index_rows_file="$(mktemp)"
# Reachability analysis: adapter entry + GC backend as additional entry
# Outputs:
#   reachable\t<idx>        — files reachable from adapter entry
#   ordered\t<idx>          — dependency-ordered files from adapter entry
#   bundle_reachable\t<idx> — files reachable from adapter entry + GC backend (for main bundle)
python3 - "$COMPILER_DIR" "$MANIFEST" "cli_adapter.vibe" >"$cli_adapter_index_rows_file" <<'PY'
import os
import re
import sys

compiler_dir, manifest_path, root_rel = sys.argv[1:]
rows = []
for raw in open(manifest_path, "r", encoding="utf-8"):
    line = raw.rstrip("\n")
    if not line or line.startswith("#"):
        continue
    parts = line.split("\t")
    if len(parts) != 2:
        continue
    rows.append((parts[0], parts[1]))

source_by_rel = {}
for _, rel in rows:
    full = os.path.join(compiler_dir, rel)
    if os.path.isfile(full):
        with open(full, "r", encoding="utf-8") as f:
            source_by_rel[rel] = f.read()

# repo-rooted ("lib/@scope/name/...") -> manifest key, mirroring the SAME
# ../../../ -> repo-root / bare -> lib/@vibe/compiler/ rule the bash bundle
# writer applies to every embedded path below (#741/#766). A `@scope/name`
# import resolves to this repo-rooted spelling (loader/header_cache.vibe's
# resolve_import_path_candidates does the identical `lib/<raw_path>/...`
# join at runtime), so this reverse index is what lets an `@`-qualified
# import find its manifest row here.
REPO_ROOTED_PREFIX = "../../../"
repo_rooted_to_rel = {}
for rel in source_by_rel:
    if rel.startswith(REPO_ROOTED_PREFIX):
        repo_rooted = rel[len(REPO_ROOTED_PREFIX):]
    else:
        repo_rooted = "lib/@vibe/compiler/" + rel
    repo_rooted_to_rel[repo_rooted] = rel

# #897/Codex: optional non-capturing `as <mod> only` tail so a qualified
# import's path capture doesn't swallow the " as h only" text as part of
# the resolved path (the qualified grammar lives in lib/@vibe/parser/parser.vibe).
dep_pattern = re.compile(r'^\s*(?:import|export)\s+([.@][\w./@\s-]+?)(?:\.vibe)?(?:\s+as\s+\w+\s+only)?\s*\{', re.MULTILINE)

def normalize_path(path: str) -> str:
    parts = []
    for seg in path.split("/"):
        if seg == "" or seg == ".":
            continue
        if seg == "..":
            if parts and parts[-1] != "..":
                parts.pop()
            else:
                parts.append("..")
            continue
        parts.append(seg)
    return "/".join(parts)

def resolve_path(base_rel: str, raw_path: str) -> str:
    base_dir = os.path.dirname(base_rel)
    raw_path = re.sub(r'\s*/\s*', '/', raw_path.strip())
    if raw_path.startswith("@"):
        # `@scope/name[/...]` package-qualified import (loader/header_cache.vibe's
        # relative-import package-boundary check requires this spelling for
        # any cross-package reference, including compiler-internal nested
        # packages -- see docs on `enforce_relative_import_package_boundary_fs`).
        # Resolves the SAME way the real runtime loader does
        # (resolve_import_path_candidates's `@` branch): `lib/<raw_path>/...`,
        # repo-rooted. Look it up via repo_rooted_to_rel (mirrors this
        # script's own ../../../ <-> lib/@vibe/compiler/ convention) to find
        # its manifest row -- whether that row is INSIDE this compiler_dir
        # tree (a compiler-internal `@vibe/compiler/<sub>` package) or a
        # sibling package under lib/ (`@vibe/core`, `@vibe/json`, ...): #1066
        # found the bundle silently dropping 18 lib/@vibe/core files (and
        # every other cross-package dep) once they switched to `@` spelling,
        # because this used to only recognize the compiler-internal case.
        # A path with no manifest row at all (genuinely external, e.g. a
        # store-pinned package with no lib/ dev-mode copy) returns unchanged,
        # naturally missing source_by_rel like it always did.
        lib_rel = "lib/" + raw_path
        for idx_candidate in (lib_rel + "/index.vpkg", lib_rel + "/index.vibei", lib_rel + "/index.vibe"):
            if idx_candidate in repo_rooted_to_rel:
                return repo_rooted_to_rel[idx_candidate]
        return raw_path
    path = raw_path if raw_path.endswith(".vibe") else raw_path + ".vibe"
    if path.startswith("./") or path.startswith("../"):
        if base_dir:
            candidate = normalize_path(base_dir + "/" + path)
        else:
            candidate = normalize_path(path)
    else:
        candidate = normalize_path(path)
    if candidate in source_by_rel:
        return candidate
    # Directory-style imports fall back to index.vpkg / index.vibei (contract
    # package, #897 Phase 1 accepts either spelling) / index.vibe
    if candidate.endswith(".vibe"):
        stem = candidate[: -len(".vibe")]
        for idx_candidate in (stem + "/index.vpkg", stem + "/index.vibei", stem + "/index.vibe"):
            if idx_candidate in source_by_rel:
                return idx_candidate
    return candidate

# Mirror the RUNTIME loader's `.vpkg` sibling auto-discovery (ADR-0070 Phase
# 1, `contract_sibling_impl_raws`/loader/header_cache.vibe): this reachability
# walk is a separate, textual-only re-implementation (it runs before any
# compiler exists, so it can't call the real desugar logic) that used to see
# a package's impl files ONLY via the contract's own `import ./x.vibe {}`
# lines. Since the runtime now auto-discovers those siblings for a `.vpkg`
# UNCONDITIONALLY regardless of whether they're declared, a `.vpkg` with no
# (or partial) explicit import lines was going stale here: this walker
# treated the undeclared siblings as unreachable dead code and silently
# pruned them from the bundle, even though the self-hosted compiler embeds
# and needs them. Fixed by having the walker ITSELF auto-discover: whenever
# it reaches a `.vpkg`, it also visits every sibling `.vibe` in that file's
# directory, using the exact same exclusion rules as the vibe-side discovery
# function.
#
# `.vibei` (legacy, loader.vibe's OTHER branch) keeps the OLD conditional
# rule instead -- auto-discover only when the contract declares NO explicit
# import lines at all; an explicit (even partial) list still means
# explicit-only, no discovery -- so a legacy package can deliberately keep an
# ordinary sibling file out of its contract (Codex review on #1054: treating
# `.vibei` the same as `.vpkg` here could pull an intentionally-excluded
# sibling into the bundle's source closure that the runtime would never load
# for that same package).
CONTRACT_SUFFIXES = (".vpkg", ".vibei")

def wants_contract_discovery(rel: str, found_deps: int) -> bool:
    if rel.endswith(".vpkg"):
        return True
    if rel.endswith(".vibei"):
        return found_deps == 0
    return False

def contract_sibling_rels(rel: str):
    real_dir = os.path.join(compiler_dir, os.path.dirname(rel))
    if not os.path.isdir(real_dir):
        return []
    base_dir = os.path.dirname(rel)
    out = []
    for name in sorted(os.listdir(real_dir)):
        if name in ("index.vpkg", "index.vibei", "index.vibe"):
            continue
        if not name.endswith(".vibe"):
            continue
        if name.endswith("_test.vibe") or name.endswith("_bench.vibe") or name.endswith(".draft.vibe"):
            continue
        if name.startswith("_"):
            continue
        out.append(normalize_path(base_dir + "/" + name) if base_dir else name)
    return out

reachable = set()

# Manifest-completeness guard (#740 follow-up): an import that resolves to a
# real file missing from the manifest is silently dropped by every walk here
# AND by the runtime manifest lane (try_collect_manifest_sources_fs), which
# surfaces much later as "undefined variable" only in cold whole-graph
# FS-compiles (this exact hole shipped double_to_string_expr.vibe without a
# manifest row). Record such edges and fail the generation instead.
manifest_gaps = {}

def record_gap(user: str, target: str):
    probes = [target]
    if target.endswith(".vibe"):
        stem = target[: -len(".vibe")]
        probes += [stem + "/index.vpkg", stem + "/index.vibei", stem + "/index.vibe"]
    for probe in probes:
        if os.path.isfile(os.path.join(compiler_dir, probe)):
            manifest_gaps.setdefault(probe, []).append(user)
            return

def visit(rel: str):
    if rel in reachable:
        return
    source = source_by_rel.get(rel)
    if source is None:
        return
    reachable.add(rel)
    found = 0
    for dep in dep_pattern.findall(source):
        found += 1
        target = resolve_path(rel, dep)
        if target not in source_by_rel:
            record_gap(rel, target)
        visit(target)
    if wants_contract_discovery(rel, found):
        for sib in contract_sibling_rels(rel):
            if sib not in source_by_rel:
                record_gap(rel, sib)
            visit(sib)

visit(root_rel)
index_by_rel = {}
for pair_index, (_, rel) in enumerate(rows):
    index_by_rel[rel] = pair_index
for idx, (_, rel) in enumerate(rows):
    if rel in reachable:
        print("reachable\t" + str(idx))

visited = set()
ordered = []

def visit_ordered(rel: str):
    if rel in visited:
        return
    source = source_by_rel.get(rel)
    if source is None:
        return
    visited.add(rel)
    found = 0
    for dep in dep_pattern.findall(source):
        found += 1
        visit_ordered(resolve_path(rel, dep))
    if wants_contract_discovery(rel, found):
        for sib in contract_sibling_rels(rel):
            visit_ordered(sib)
    ordered.append(rel)

visit_ordered(root_rel)
for rel in ordered:
    idx = index_by_rel.get(rel)
    if idx is not None:
        print("ordered\t" + str(idx))

# Bundle reachability: adapter entry + GC backend
bundle_reachable = set(reachable)

def visit_bundle(rel: str):
    if rel in bundle_reachable:
        return
    source = source_by_rel.get(rel)
    if source is None:
        return
    bundle_reachable.add(rel)
    found = 0
    for dep in dep_pattern.findall(source):
        found += 1
        target = resolve_path(rel, dep)
        if target not in source_by_rel:
            record_gap(rel, target)
        visit_bundle(target)
    if wants_contract_discovery(rel, found):
        for sib in contract_sibling_rels(rel):
            if sib not in source_by_rel:
                record_gap(rel, sib)
            visit_bundle(sib)

# Additional entry points for the main bundle
bundle_extra_entries = os.environ.get("VIBE_BUNDLE_EXTRA_ENTRIES", "codegen/gc/index.vibe,index.vibe")
for entry in bundle_extra_entries.split(","):
    entry = entry.strip()
    if entry:
        visit_bundle(entry)

if manifest_gaps:
    for target, users in sorted(manifest_gaps.items()):
        sys.stderr.write(
            "error: "
            + target
            + " is imported by "
            + ", ".join(sorted(set(users)))
            + " but has no row in compiler_sources_manifest.tsv; add one or the"
            + " manifest FS-compile lane silently drops it (#740)\n"
        )
    sys.exit(1)

for idx, (_, rel) in enumerate(rows):
    if rel in bundle_reachable:
        print("bundle_reachable\t" + str(idx))
PY
CLI_ADAPTER_INDEXES=()
CLI_ADAPTER_ORDERED_INDEXES=()
BUNDLE_REACHABLE_INDEXES=()
while IFS=$'\t' read -r kind idx; do
  if [ -z "${kind}${idx}" ]; then
    continue
  fi
  if [ "$kind" = "reachable" ]; then
    CLI_ADAPTER_INDEXES+=("$idx")
  elif [ "$kind" = "ordered" ]; then
    CLI_ADAPTER_ORDERED_INDEXES+=("$idx")
  elif [ "$kind" = "bundle_reachable" ]; then
    BUNDLE_REACHABLE_INDEXES+=("$idx")
  fi
done < "$cli_adapter_index_rows_file"
rm -f "$cli_adapter_index_rows_file"

main_index_rows_file="$(mktemp)"
python3 - "$COMPILER_DIR" "$MANIFEST" "compiler.vibe" >"$main_index_rows_file" <<'PY'
import os
import re
import sys

compiler_dir, manifest_path, root_rel = sys.argv[1:]
rows = []
for raw in open(manifest_path, "r", encoding="utf-8"):
    line = raw.rstrip("\n")
    if not line or line.startswith("#"):
        continue
    parts = line.split("\t")
    if len(parts) != 2:
        continue
    rows.append((parts[0], parts[1]))

source_by_rel = {}
for _, rel in rows:
    full = os.path.join(compiler_dir, rel)
    if os.path.isfile(full):
        with open(full, "r", encoding="utf-8") as f:
            source_by_rel[rel] = f.read()

# repo-rooted ("lib/@scope/name/...") -> manifest key, mirroring the SAME
# ../../../ -> repo-root / bare -> lib/@vibe/compiler/ rule the bash bundle
# writer applies to every embedded path below (#741/#766). A `@scope/name`
# import resolves to this repo-rooted spelling (loader/header_cache.vibe's
# resolve_import_path_candidates does the identical `lib/<raw_path>/...`
# join at runtime), so this reverse index is what lets an `@`-qualified
# import find its manifest row here.
REPO_ROOTED_PREFIX = "../../../"
repo_rooted_to_rel = {}
for rel in source_by_rel:
    if rel.startswith(REPO_ROOTED_PREFIX):
        repo_rooted = rel[len(REPO_ROOTED_PREFIX):]
    else:
        repo_rooted = "lib/@vibe/compiler/" + rel
    repo_rooted_to_rel[repo_rooted] = rel

# #897/Codex: optional non-capturing `as <mod> only` tail so a qualified
# import's path capture doesn't swallow the " as h only" text as part of
# the resolved path (the qualified grammar lives in lib/@vibe/parser/parser.vibe).
dep_pattern = re.compile(r'^\s*(?:import|export)\s+([.@][\w./@\s-]+?)(?:\.vibe)?(?:\s+as\s+\w+\s+only)?\s*\{', re.MULTILINE)

def normalize_path(path: str) -> str:
    parts = []
    for seg in path.split("/"):
        if seg == "" or seg == ".":
            continue
        if seg == "..":
            if parts and parts[-1] != "..":
                parts.pop()
            else:
                parts.append("..")
            continue
        parts.append(seg)
    return "/".join(parts)

def resolve_path(base_rel: str, raw_path: str) -> str:
    base_dir = os.path.dirname(base_rel)
    raw_path = re.sub(r'\s*/\s*', '/', raw_path.strip())
    if raw_path.startswith("@"):
        # `@scope/name[/...]` package-qualified import (loader/header_cache.vibe's
        # relative-import package-boundary check requires this spelling for
        # any cross-package reference, including compiler-internal nested
        # packages -- see docs on `enforce_relative_import_package_boundary_fs`).
        # Resolves the SAME way the real runtime loader does
        # (resolve_import_path_candidates's `@` branch): `lib/<raw_path>/...`,
        # repo-rooted. Look it up via repo_rooted_to_rel (mirrors this
        # script's own ../../../ <-> lib/@vibe/compiler/ convention) to find
        # its manifest row -- whether that row is INSIDE this compiler_dir
        # tree (a compiler-internal `@vibe/compiler/<sub>` package) or a
        # sibling package under lib/ (`@vibe/core`, `@vibe/json`, ...): #1066
        # found the bundle silently dropping 18 lib/@vibe/core files (and
        # every other cross-package dep) once they switched to `@` spelling,
        # because this used to only recognize the compiler-internal case.
        # A path with no manifest row at all (genuinely external, e.g. a
        # store-pinned package with no lib/ dev-mode copy) returns unchanged,
        # naturally missing source_by_rel like it always did.
        lib_rel = "lib/" + raw_path
        for idx_candidate in (lib_rel + "/index.vpkg", lib_rel + "/index.vibei", lib_rel + "/index.vibe"):
            if idx_candidate in repo_rooted_to_rel:
                return repo_rooted_to_rel[idx_candidate]
        return raw_path
    path = raw_path if raw_path.endswith(".vibe") else raw_path + ".vibe"
    if path.startswith("./") or path.startswith("../"):
        if base_dir:
            candidate = normalize_path(base_dir + "/" + path)
        else:
            candidate = normalize_path(path)
    else:
        candidate = normalize_path(path)
    if candidate in source_by_rel:
        return candidate
    if candidate.endswith(".vibe"):
        stem = candidate[: -len(".vibe")]
        for idx_candidate in (stem + "/index.vpkg", stem + "/index.vibei", stem + "/index.vibe"):
            if idx_candidate in source_by_rel:
                return idx_candidate
    return candidate

# See the matching helper in the cli_adapter.vibe walk above: mirrors the
# runtime loader's `.vpkg` sibling auto-discovery (unconditional) vs legacy
# `.vibei` (only when no explicit import lines) so this textual walk doesn't
# silently prune undeclared-but-real siblings, nor pull in a sibling a legacy
# `.vibei` deliberately left out of its contract.
CONTRACT_SUFFIXES = (".vpkg", ".vibei")

def wants_contract_discovery(rel: str, found_deps: int) -> bool:
    if rel.endswith(".vpkg"):
        return True
    if rel.endswith(".vibei"):
        return found_deps == 0
    return False

def contract_sibling_rels(rel: str):
    real_dir = os.path.join(compiler_dir, os.path.dirname(rel))
    if not os.path.isdir(real_dir):
        return []
    base_dir = os.path.dirname(rel)
    out = []
    for name in sorted(os.listdir(real_dir)):
        if name in ("index.vpkg", "index.vibei", "index.vibe"):
            continue
        if not name.endswith(".vibe"):
            continue
        if name.endswith("_test.vibe") or name.endswith("_bench.vibe") or name.endswith(".draft.vibe"):
            continue
        if name.startswith("_"):
            continue
        out.append(normalize_path(base_dir + "/" + name) if base_dir else name)
    return out

index_by_rel = {}
for pair_index, (_, rel) in enumerate(rows):
    index_by_rel[rel] = pair_index

visited = set()
ordered = []

def visit_ordered(rel: str):
    if rel in visited:
        return
    source = source_by_rel.get(rel)
    if source is None:
        return
    visited.add(rel)
    found = 0
    for dep in dep_pattern.findall(source):
        found += 1
        visit_ordered(resolve_path(rel, dep))
    if wants_contract_discovery(rel, found):
        for sib in contract_sibling_rels(rel):
            visit_ordered(sib)
    ordered.append(rel)

visit_ordered(root_rel)
for rel in ordered:
    idx = index_by_rel.get(rel)
    if idx is not None:
        print(idx)
PY
MAIN_ORDERED_INDEXES=()
while IFS= read -r idx; do
  if [ -n "${idx}" ]; then
    MAIN_ORDERED_INDEXES+=("$idx")
  fi
done < "$main_index_rows_file"
rm -f "$main_index_rows_file"

# Build lookup set for bundle reachability filter
is_bundle_reachable() {
  local target="$1"
  local idx
  for idx in "${BUNDLE_REACHABLE_INDEXES[@]}"; do
    if [ "$idx" = "$target" ]; then
      return 0
    fi
  done
  return 1
}

if [ "${#FILES[@]}" -eq 0 ]; then
  echo "error: manifest contains no compiler sources: $MANIFEST" >&2
  exit 1
fi

find_adapter_local_index() {
  local target="$1"
  local i=0
  local idx
  for idx in "${CLI_ADAPTER_INDEXES[@]}"; do
    if [ "$idx" = "$target" ]; then
      echo "$i"
      return 0
    fi
    i=$((i + 1))
  done
  return 1
}

find_bundle_local_index() {
  local target="$1"
  local pair manifest_idx local_idx
  for pair in "${BUNDLE_SOURCE_INDEXES[@]}"; do
    manifest_idx="${pair%%:*}"
    local_idx="${pair#*:}"
    if [ "$manifest_idx" = "$target" ]; then
      echo "$local_idx"
      return 0
    fi
  done
  return 1
}

is_main_ordered() {
  local target="$1"
  local idx
  for idx in "${MAIN_ORDERED_INDEXES[@]}"; do
    if [ "$idx" = "$target" ]; then
      return 0
    fi
  done
  return 1
}

write_vibe_string_literal_from_file() {
  local filepath="$1"
  python3 - "$filepath" <<'PY'
import sys

with open(sys.argv[1], "r", encoding="utf-8") as f:
    content = f.read()
content = content.replace("\\", "\\\\")
content = content.replace('"', '\\"')
content = content.replace("\n", "\\n")
sys.stdout.write('"' + content + '"')
PY
}

write_vibe_chunked_string_function_from_file() {
  local prefix="$1"
  local export_name="$2"
  local filepath="${3:-}"
  local chunk_size="${VIBE_BUNDLE_CHUNK_SIZE:-8192}"
  if [ -z "$filepath" ] || [ ! -f "$filepath" ]; then
    echo "export let $export_name = () -> String {"
    echo "  \"\""
    echo "}"
    return 0
  fi
  python3 - "$filepath" "$prefix" "$export_name" "$chunk_size" <<'PY'
import sys

filepath, prefix, export_name, chunk_size = sys.argv[1:]
chunk_size = int(chunk_size)
with open(filepath, "r", encoding="utf-8") as f:
    content = f.read()

def esc(text: str) -> str:
    text = text.replace("\\", "\\\\")
    text = text.replace('"', '\\"')
    text = text.replace("\n", "\\n")
    return text

chunks = [content[i:i + chunk_size] for i in range(0, len(content), chunk_size)]
if not chunks:
    chunks = [""]

print(f"export let {export_name} = () -> String {{")
if len(chunks) == 1:
    print(f'  "{esc(chunks[0])}"')
else:
    print("  let sb = StringBuilder::new()")
    for chunk in chunks:
        print(f'  StringBuilder::push(sb, "{esc(chunk)}")')
    print("  StringBuilder::freeze(sb)")
print("}")
PY
}

write_vibe_string_function_from_file() {
  local binding_name="$1"
  local export_name="$2"
  local filepath="${3:-}"
  if [ -z "$filepath" ] || [ ! -f "$filepath" ]; then
    echo "export let $export_name = () -> String {"
    echo "  \"\""
    echo "}"
    return 0
  fi
  echo "export let $export_name = () -> String {"
  printf '  '
  write_vibe_string_literal_from_file "$filepath"
  echo ""
  echo "}"
}

run_host_vibe_cmd() {
  local cmd="$1"
  shift
  if [ "$cmd" = "emit-module-source" ]; then
    # #594 Stage 1b/seed-bump: the selfhost seed compiler carries
    # emit-module-source (VIBE_EMIT_MODULE_SOURCE mode), so the flat module
    # source needs no MoonBit host. Args are (input, output, entry), rewritten
    # to repo-root-relative for the wasm preopen. The former fallbacks —
    # `_build/native/**/vibe.exe` and `moon build/run src/cmd/vibe`, selected by
    # VIBE_EMIT_VIA_HOST=1 — were retired with the MoonBit host: nothing in this
    # repo can build that binary any more, so the seed is the only path.
    local seed_wasm="$SCRIPT_PROJECT_ROOT/bootstrap/seed/compiler.wasm"
    if [ -f "$seed_wasm" ]; then
      local emit_in="${1#"$SCRIPT_PROJECT_ROOT"/}"
      local emit_out="${2#"$SCRIPT_PROJECT_ROOT"/}"
      local emit_entry="${3:-cli_main}"
      (
        cd "$SCRIPT_PROJECT_ROOT" &&
          VIBE_PREOPEN_DIR="$SCRIPT_PROJECT_ROOT" \
            VIBE_EMIT_MODULE_SOURCE=1 \
            VIBE_IMPORT_ABI="${VIBE_IMPORT_ABI:-raw}" \
            bash "$SCRIPT_PROJECT_ROOT/scripts/run_wasm_vibe_host_runner.sh" \
            --invoke cli_main "$seed_wasm" "$emit_in" "$emit_out" "$emit_entry"
      )
      return 0
    fi
    echo "generate_bundle: emit-module-source needs the seed compiler at $seed_wasm (run scripts/ensure_seed.sh)" >&2
    return 1
  fi
  echo "generate_bundle: no host compiler for '$cmd' — the MoonBit host was retired (#594); only emit-module-source is served, via the seed" >&2
  return 1
}

build_adapter_module_source() {
  local merged_source_file="$1"
  # Fast path for tiny shell self-tests; production generation uses
  # emit-module-source through the host compiler below.
  if [ "${VIBE_ADAPTER_MODULE_SOURCE_FROM_MERGED:-0}" = "1" ]; then
    local module_source_path
    mkdir -p "$PROJECT_ROOT/_build"
    module_source_path="$(mktemp "$PROJECT_ROOT/_build/cli_adapter_module_source.XXXXXX")"
    python3 - "$merged_source_file" "$module_source_path" <<'PY'
import sys

src, out = sys.argv[1:]
with open(src, "r", encoding="utf-8") as f:
    lines = f.readlines()

with open(out, "w", encoding="utf-8") as f:
    for line in lines:
        stripped = line.lstrip()
        if stripped.startswith("let ") and "->" not in stripped:
            continue
        f.write(line)
PY
    printf '%s\n' "$module_source_path"
    return 0
  fi
  # The flat module source is a deterministic function of the compiler source,
  # so it is ALWAYS regenerated here. It used to be read back from the committed
  # _cli_adapter_module_source.vibe unless VIBE_REGEN_MODULE_SOURCE=1 was set --
  # a silent staleness trap: a source edit that nobody thought to regenerate for
  # produced a compiler WITHOUT that edit, and the build reported success. (Cost
  # of that trap, measured: three full rebuilds spent measuring a compiler that
  # did not contain the change under test.) Freshness is now decided ONCE, by
  # fingerprint, in scripts/ensure_generated.sh -- reaching this function at all
  # means the answer was already "regenerate".
  local module_source_path
  mkdir -p "$PROJECT_ROOT/_build"
  module_source_path="$(mktemp "$PROJECT_ROOT/_build/cli_adapter_module_source.XXXXXX")"
  # #1137: DCE-root at "main" (cli_adapter.vibe), not "cli_main" -- `main`'s
  # own body calls `cli_main()` directly, so the existing (unmodified,
  # seed-compatible) reachability walk in core/dce.vibe follows that
  # reference and keeps `cli_main` alive too (a strict superset of what
  # "cli_main" alone would keep). Rooting at "cli_main" instead would DCE
  # `main` away entirely, since cli_main never references it back. This
  # relies on no new emit-module-source behavior, so it works against the
  # currently-pinned seed with no bootstrap bump.
  run_host_vibe_cmd emit-module-source "$merged_source_file" "$module_source_path" "main" >/dev/null
  printf '%s\n' "$module_source_path"
}

write_adapter_bundle() {
  local merged_source_file="${1:-}"
  local module_source_file="${2:-}"
  {
  echo "// AUTO-GENERATED by scripts/generate_bundle.sh"
  echo "// Do not edit manually. Regenerate with: bash scripts/generate_bundle.sh"
  echo ""
  echo "//# CLI adapter bundle"
  echo ""
  echo "let cli_adapter_empty_grouped_sources = () -> Array[(String, Array[(String, String)])] {"
  echo "  Array::slice([(\"\", Array::slice([(\"\", \"\")], 0, 0))], 0, 0)"
  echo "}"
  echo ""
  echo "let cli_adapter_push_grouped_source_pair = (groups: Array[(String, Array[(String, String)])], group_name: String, pair: (String, String)) -> Unit {"
  echo "  let (path, source) = pair"
  echo "  let mut i = 0"
  echo "  let mut found = false"
  echo "  while i < Array::length(groups) {"
  echo "    let (name, sources) = Array::get(groups, i)"
  echo "    if String::equals(name, group_name) {"
  echo "      Array::push(sources, (path, source))"
  echo "      found = true"
  echo "      i = Array::length(groups)"
  echo "    } else {"
  echo "      i = i + 1"
  echo "    }"
  echo "  }"
  echo "  if !found {"
  echo "    let sources = Array::slice([(\"\", \"\")], 0, 0)"
  echo "    Array::push(sources, (path, source))"
  echo "    Array::push(groups, (group_name, sources))"
  echo "  }"
  echo "}"
  echo ""

  adapter_local_idx=0
  for idx in "${CLI_ADAPTER_INDEXES[@]}"; do
    f="${FILES[$idx]}"
    filepath="$COMPILER_DIR/$f"
    # #741/#766: manifest rows outside the compiler dir (../../../lib/@vibe/core/...)
    # are repo-rooted once the ../../../ prefix (lib/@vibe/compiler -> repo root) drops.
    if [[ "$f" == ../../../* ]]; then
      relpath="${f#../../../}"
    else
      relpath="lib/@vibe/compiler/$f"
    fi
    echo "let cli_adapter_source_$adapter_local_idx = () -> (String, String) {"
    echo "  (\"$relpath\","
    write_vibe_string_literal_from_file "$filepath"
    echo ")"
    echo "}"
    echo ""
    adapter_local_idx=$((adapter_local_idx + 1))
  done

  echo "export let cli_adapter_sources = () -> Array[(String, String)] {"
  echo "  let sources = Array::slice([(\"\", \"\")], 0, 0)"
  adapter_local_idx=0
  for _idx in "${CLI_ADAPTER_INDEXES[@]}"; do
    echo "  Array::push(sources, cli_adapter_source_$adapter_local_idx())"
    adapter_local_idx=$((adapter_local_idx + 1))
  done
  echo "  sources"
  echo "}"
  echo ""
  echo "export let cli_adapter_source_groups = () -> Array[(String, Array[(String, String)])] {"
  echo "  let groups = cli_adapter_empty_grouped_sources()"
  adapter_local_idx=0
  for idx in "${CLI_ADAPTER_INDEXES[@]}"; do
    group="${MANIFEST_GROUPS[$idx]}"
    echo "  cli_adapter_push_grouped_source_pair(groups, \"$group\", cli_adapter_source_$adapter_local_idx())"
    adapter_local_idx=$((adapter_local_idx + 1))
  done
  echo "  groups"
  echo "}"
  echo ""
  echo "export let cli_adapter_ordered_sources = () -> Array[(String, String)] {"
  echo "  let sources = Array::slice([(\"\", \"\")], 0, 0)"
  for idx in "${CLI_ADAPTER_ORDERED_INDEXES[@]}"; do
    adapter_local_idx="$(find_adapter_local_index "$idx")"
    echo "  Array::push(sources, cli_adapter_source_$adapter_local_idx())"
  done
  echo "  sources"
  echo "}"
  echo ""
  write_vibe_string_function_from_file \
    "cli_adapter_merged_source_value" \
    "cli_adapter_merged_source" \
    "$merged_source_file"
  echo ""
  write_vibe_string_function_from_file \
    "cli_adapter_module_source_value" \
    "cli_adapter_module_source" \
    "$module_source_file"
  } > "$OUT_ADAPTER"
}

write_runtime_entry_bundle() {
  {
  echo "// AUTO-GENERATED by scripts/generate_bundle.sh"
  echo "// Do not edit manually. Regenerate with: bash scripts/generate_bundle.sh"
  echo ""
  echo "//# Selfbuild runtime entry bundle"
  echo ""
  write_vibe_chunked_string_function_from_file \
    "selfbuild_runtime_entry_source" \
    "selfbuild_runtime_entry_source" \
    "$COMPILER_DIR/_selfbuild_runtime_entry.vibe"
  } > "$OUT_RUNTIME_ENTRY"
}

# #726: flatten via the compiler's OWN merge machinery (ExportRenamePlan +
# private namespacing), replacing the Python flattener that stripped
# import/export lines and concatenated files, leaving duplicate top-level defs
# resolved by fn-table first-match. The merge renames them, so the flat source
# has ZERO duplicates (asserted by the caller) and carries #716's visibility
# guarantees.
#
# The flatten TOOL is the current source's merge machinery, compiled by the
# seed -- "one generation back", the same discipline the seed itself follows.
# It used to be built from the COMMITTED _cli_adapter_module_source.vibe, which
# is what forced that 4MB artifact to be tracked: regenerating it needed a copy
# of itself.
#
# That was never a real cycle. The pinned seed can resolve imports off the live
# tree and print the merged program on its own (VIBE_EMIT_MERGED_SOURCE), so the
# tool can be bootstrapped from source in two extra seed passes and the
# committed copy drops out entirely -- see scripts/ensure_generated.sh and
# docs/bootstrap.md. Verified when this landed: the tool built this way produces
# a merged source BYTE-IDENTICAL to the one built from the committed artifact.
#
# The seed's own flatten is deliberately NOT used for the final output. It would
# be one generation older, so an edit to the merge machinery itself
# (merge_sources.vibe / import_alias_rewrite.vibe) would not take effect until
# the next seed bump -- silently, since the output would still be valid. Paying
# two extra seed passes keeps "edit the merge, regenerate, see it" true.
bootstrap_merge_flatten_tool() {
  local flatten_wasm="$1"
  local seed_wasm="$PROJECT_ROOT/bootstrap/seed/compiler.wasm"
  local tool_node_flags="${VIBE_NODE_WASM_FLAGS:---experimental-wasm-exnref --stack-size=${VIBE_GENERATION_NODE_STACK_SIZE:-131072}}"
  local tool_log="$PROJECT_ROOT/_build/merge_flatten_compiler.log"
  local seed_merged seed_modsrc
  seed_merged="$(mktemp "$PROJECT_ROOT/_build/seed_merged_source.XXXXXX")"
  seed_modsrc="$(mktemp "$PROJECT_ROOT/_build/seed_module_source.XXXXXX")"
  # Pass 1: the seed flattens the live tree.
  rm -f "$seed_merged" "$seed_merged.diag"
  (cd "$PROJECT_ROOT" && env VIBE_EMIT_MERGED_SOURCE=1 VIBE_PREOPEN_DIR="$PROJECT_ROOT" \
    VIBE_IMPORT_ABI="${VIBE_IMPORT_ABI:-raw}" \
    VIBE_NODE_WASM_FLAGS="$tool_node_flags" \
    bash scripts/run_wasm_vibe_host_runner.sh --invoke cli_main "$seed_wasm" \
    lib/@vibe/compiler/cli_adapter.vibe "$seed_merged" cli_main >"$tool_log.seedflat" 2>&1) || true
  if [ ! -s "$seed_merged" ]; then
    echo "generate_bundle: seed could not flatten the live tree (bootstrap pass 1)" >&2
    cat "$seed_merged.diag" >&2 2>/dev/null || true
    tail -40 "$tool_log.seedflat" >&2 2>/dev/null || true
    exit 1
  fi
  # Pass 2: DCE it to a module source the seed can compile (same rooting as the
  # real emit below -- see the #1137 note in build_adapter_module_source).
  run_host_vibe_cmd emit-module-source "$seed_merged" "$seed_modsrc" "main" >/dev/null
  if [ ! -s "$seed_modsrc" ]; then
    echo "generate_bundle: emit-module-source failed on the seed-flattened source (bootstrap pass 2)" >&2
    exit 1
  fi
  # Pass 3: compile it -- this is the current source's merge machinery.
  rm -f "$flatten_wasm" "$flatten_wasm.diag"
  (cd "$PROJECT_ROOT" && env VIBE_RC=0 VIBE_PREOPEN_DIR="$PROJECT_ROOT" \
    VIBE_IMPORT_ABI="${VIBE_IMPORT_ABI:-raw}" \
    VIBE_NODE_WASM_FLAGS="$tool_node_flags" \
    bash scripts/run_wasm_vibe_host_runner.sh --invoke cli_main "$seed_wasm" \
    "$seed_modsrc" "$flatten_wasm" cli_main >"$tool_log" 2>&1) || true
  rm -f "$seed_merged" "$seed_merged.diag" "$seed_modsrc" "$seed_modsrc.diag"
}

build_exact_adapter_merged_source() {
  local merged_path
  mkdir -p "$PROJECT_ROOT/_build"
  merged_path="$(mktemp "$PROJECT_ROOT/_build/cli_adapter_merged_source.XXXXXX")"
  local flatten_wasm="$PROJECT_ROOT/_build/merge_flatten_compiler.wasm"
  local tool_node_flags="${VIBE_NODE_WASM_FLAGS:---experimental-wasm-exnref --stack-size=${VIBE_GENERATION_NODE_STACK_SIZE:-131072}}"
  local tool_log="$PROJECT_ROOT/_build/merge_flatten_compiler.log"
  bootstrap_merge_flatten_tool "$flatten_wasm"
  if [ ! -s "$flatten_wasm" ]; then
    echo "generate_bundle: merge-flatten compiler build failed" >&2
    cat "$flatten_wasm.diag" >&2 2>/dev/null || true
    echo "--- runner output ---" >&2
    tail -40 "$tool_log" >&2 2>/dev/null || true
    exit 1
  fi
  rm -f "$merged_path.diag"
  (cd "$PROJECT_ROOT" && env VIBE_EMIT_MERGED_SOURCE=1 VIBE_PREOPEN_DIR="$PROJECT_ROOT" \
    VIBE_IMPORT_ABI="${VIBE_IMPORT_ABI:-raw}" \
    VIBE_NODE_WASM_FLAGS="$tool_node_flags" \
    bash scripts/run_wasm_vibe_host_runner.sh --invoke cli_main "$flatten_wasm" \
    lib/@vibe/compiler/cli_adapter.vibe "$merged_path" cli_main >"$tool_log.flatten" 2>&1) || true
  if [ ! -s "$merged_path" ]; then
    echo "generate_bundle: merge flatten failed" >&2
    cat "$merged_path.diag" >&2 2>/dev/null || true
    echo "--- runner output ---" >&2
    tail -40 "$tool_log.flatten" >&2 2>/dev/null || true
    exit 1
  fi
  # #726 gate: the merged flat source must have ZERO duplicate top-level defs.
  local dups
  dups="$(grep -E '^(export )?let (rec )?(mut )?[A-Za-z_]' "$merged_path" \
    | sed -E 's/^(export )?let (rec )?(mut )?([A-Za-z_][A-Za-z0-9_:#]*).*/\4/' \
    | sort | uniq -d | wc -l | tr -d ' ')"
  if [ "$dups" != "0" ]; then
    echo "generate_bundle: $dups duplicate top-level def(s) in merged source (#726)" >&2
    grep -E '^(export )?let (rec )?(mut )?[A-Za-z_]' "$merged_path" \
      | sed -E 's/^(export )?let (rec )?(mut )?([A-Za-z_][A-Za-z0-9_:#]*).*/\4/' \
      | sort | uniq -d >&2
    exit 1
  fi
  printf '%s\n' "$merged_path"
}

# #979: writing $ADAPTER_MODULE_SOURCE_OUT (normally
# lib/@vibe/compiler/_cli_adapter_module_source.vibe, the committed flat
# module source stage1/stage2 bootstrap FROM) used to `cp` the freshly
# flattened candidate straight over the real destination with no check that
# it actually compiles. A bad flatten (e.g. the merge/printer surfacing a
# pre-existing parser bug) left a BROKEN file committed on disk; every
# subsequent regen rebuilds the merge-flatten tool FROM that same broken
# committed file (see build_exact_adapter_merged_source above), so the
# failure was self-perpetuating -- recoverable only via `git checkout HEAD
# -- lib/@vibe/compiler/_cli_adapter_module_source.vibe`. Make the write
# atomic and gated: compile-check the CANDIDATE with the seed compiler in a
# throwaway tmp file first, and only `mv` the candidate into place (same
# dir, so the rename is atomic) when that succeeds; otherwise leave
# whatever was already at $ADAPTER_MODULE_SOURCE_OUT untouched and fail
# loudly. When no seed wasm is available (e.g. tiny synthetic fixtures used
# by generate_bundle_test.sh, which have no bootstrap/seed/ at all) the
# check is skipped -- same "trust the pinned artifact" fallback
# the retired check_module_source_sync.sh used -- so this adds no new
# dependency, only a safety gate where the seed is present.
validate_module_source_compiles() {
  local candidate="$1"
  local seed_wasm="$PROJECT_ROOT/bootstrap/seed/compiler.wasm"
  if [ ! -f "$seed_wasm" ]; then
    return 0
  fi
  mkdir -p "$PROJECT_ROOT/_build"
  local check_wasm
  check_wasm="$(mktemp "$PROJECT_ROOT/_build/module_source_validate.XXXXXX.wasm")"
  local check_log="$check_wasm.log"
  rm -f "$check_wasm"
  local tool_node_flags="${VIBE_NODE_WASM_FLAGS:---experimental-wasm-exnref --stack-size=${VIBE_GENERATION_NODE_STACK_SIZE:-131072}}"
  local ok=0
  # This is a FULL seed compile of the candidate module source -- structurally
  # the same work as a stage hop, not bundle bookkeeping. It gets its own span
  # because "prepare flat source is 77s" (docs/tracing-design.md §5.8) reads as
  # a slow shell script until you see how much of it is this.
  trace_begin "validate module source (seed compile)"
  local vtok="$TRACE_TOKEN"
  if (cd "$PROJECT_ROOT" && env VIBE_RC=0 VIBE_PREOPEN_DIR="$PROJECT_ROOT" \
    VIBE_IMPORT_ABI="${VIBE_IMPORT_ABI:-raw}" \
    VIBE_NODE_WASM_FLAGS="$tool_node_flags" \
    bash scripts/run_wasm_vibe_host_runner.sh --invoke cli_main "$seed_wasm" \
    "$candidate" "$check_wasm" cli_main >"$check_log" 2>&1); then
    if [ -s "$check_wasm" ]; then
      ok=1
    fi
  fi
  trace_end "$vtok" "$(( ok == 1 ? 0 : 1 ))"
  if [ "$ok" != "1" ]; then
    echo "generate_bundle: candidate module source failed to compile (#979 sticky-failure guard) -- leaving any existing $ADAPTER_MODULE_SOURCE_OUT untouched" >&2
    cat "$check_wasm.diag" >&2 2>/dev/null || true
    echo "--- runner output ---" >&2
    tail -40 "$check_log" >&2 2>/dev/null || true
  fi
  rm -f "$check_wasm" "$check_wasm.diag" "$check_log"
  [ "$ok" = "1" ]
}

write_adapter_bundle "" ""
ADAPTER_MERGED_SOURCE_FILE="$(build_exact_adapter_merged_source)"
ADAPTER_MODULE_SOURCE_FILE="$(build_adapter_module_source "$ADAPTER_MERGED_SOURCE_FILE")"
if [ -n "$ADAPTER_MODULE_SOURCE_OUT" ]; then
  if ! validate_module_source_compiles "$ADAPTER_MODULE_SOURCE_FILE"; then
    exit 1
  fi
  mkdir -p "$(dirname "$ADAPTER_MODULE_SOURCE_OUT")"
  ADAPTER_MODULE_SOURCE_OUT_TMP="$(mktemp "$(dirname "$ADAPTER_MODULE_SOURCE_OUT")/.$(basename "$ADAPTER_MODULE_SOURCE_OUT").XXXXXX")"
  cp "$ADAPTER_MODULE_SOURCE_FILE" "$ADAPTER_MODULE_SOURCE_OUT_TMP"
  mv "$ADAPTER_MODULE_SOURCE_OUT_TMP" "$ADAPTER_MODULE_SOURCE_OUT"
fi
write_adapter_bundle "$ADAPTER_MERGED_SOURCE_FILE" "$ADAPTER_MODULE_SOURCE_FILE"
write_runtime_entry_bundle

{
  echo "// AUTO-GENERATED by scripts/generate_bundle.sh"
  echo "// Do not edit manually. Regenerate with: bash scripts/generate_bundle.sh"
  echo ""
  echo "//# Compiler source bundle"
  echo ""
  echo "// All compiler source files bundled as (path, source) pairs."
  echo "// Used by selfbuild_compile_stage2 to avoid filesystem access."
  echo "let empty_grouped_sources = () -> Array[(String, Array[(String, String)])] {"
  echo "  Array::slice([(\"\", Array::slice([(\"\", \"\")], 0, 0))], 0, 0)"
  echo "}"
  echo ""
  echo "let push_grouped_source_pair = (groups: Array[(String, Array[(String, String)])], group_name: String, pair: (String, String)) -> Unit {"
  echo "  let (path, source) = pair"
  echo "  let mut i = 0"
  echo "  let mut found = false"
  echo "  while i < Array::length(groups) {"
  echo "    let (name, sources) = Array::get(groups, i)"
  echo "    if String::equals(name, group_name) {"
  echo "      Array::push(sources, (path, source))"
  echo "      found = true"
  echo "      i = Array::length(groups)"
  echo "    } else {"
  echo "      i = i + 1"
  echo "    }"
  echo "  }"
  echo "  if !found {"
  echo "    let sources = Array::slice([(\"\", \"\")], 0, 0)"
  echo "    Array::push(sources, (path, source))"
  echo "    Array::push(groups, (group_name, sources))"
  echo "  }"
  echo "}"
  echo ""
  # Only include files reachable from entry points (adapter + GC backend)
  BUNDLE_SOURCE_INDEXES=()
  bundle_local_idx=0
  idx=0
  for f in "${FILES[@]}"; do
    if ! is_bundle_reachable "$idx"; then
      idx=$((idx + 1))
      continue
    fi
    if [ "$f" = "cli_adapter_bundle.vibe" ]; then
      filepath="$OUT_ADAPTER"
    elif [ "$f" = "selfbuild_runtime_entry_bundle.vibe" ]; then
      filepath="$OUT_RUNTIME_ENTRY"
    else
      filepath="$COMPILER_DIR/$f"
    fi
    if [ ! -f "$filepath" ]; then
      echo "error: file not found: $filepath" >&2
      exit 1
    fi
    # #741/#766: manifest rows outside the compiler dir (../../../lib/@vibe/core/...)
    # are repo-rooted once the ../../../ prefix (lib/@vibe/compiler -> repo root) drops.
    if [[ "$f" == ../../../* ]]; then
      relpath="${f#../../../}"
    else
      relpath="lib/@vibe/compiler/$f"
    fi
    echo "let source_$bundle_local_idx = () -> (String, String) {"
    echo "  (\"$relpath\","
    # Escape the source code for embedding in a vibe string literal
    # Need to escape: backslash -> \\, double quote -> \", newline -> \n
    python3 -c "
import sys, re
with open('$filepath', 'r') as f:
    content = f.read()
# Strip relative import/export statements (they are resolved by collect_merged_stmts)
# -- EXCEPT in .vibei/.vpkg contracts (#897 Phase 1 accepts either spelling):
# there the 'import ./impl.vibe {}' lines are the contract's implementation-file
# DECLARATIONS (data consumed by the conformance desugar, loader/index.vibe
# desugar_contract_source_fs). Stripping them flipped the desugar into sibling
# auto-discovery (Fs::readdir over the whole package dir), which pulled
# deliberately-out-of-contract files like @vibe/core/map.vibe into the
# conformance set and failed the bundle-ingest lane with 'exported X is not
# declared in the contract' (s5_test). Embed .vibei/.vpkg verbatim.
drop_pattern = re.compile(r'^\s*(?:import|export)\s+\.[\w./\s-]+')
if '$filepath'.endswith('.vibei') or '$filepath'.endswith('.vpkg'):
    pass
else:
    lines = content.splitlines(True)
    out = []
    skipping = False
    depth = 0
    for line in lines:
        stripped = line.lstrip()
        if stripped.startswith('//'): continue
        if not skipping and drop_pattern.match(line):
            depth = line.count('{') - line.count('}')
            if depth > 0: skipping = True
            continue
        if skipping:
            depth += line.count('{') - line.count('}')
            if depth <= 0: skipping = False
            continue
        out.append(line)
    content = ''.join(out)
# Escape for vibe string literal
content = content.replace('\\\\', '\\\\\\\\')
content = content.replace('\"', '\\\\\"')
content = content.replace('\n', '\\\\n')
sys.stdout.write('\"' + content + '\"')
"
    echo ")"
    echo "}"
    echo ""
    BUNDLE_SOURCE_INDEXES+=("$idx:$bundle_local_idx")
    bundle_local_idx=$((bundle_local_idx + 1))
    idx=$((idx + 1))
  done

  echo "export let compiler_sources = () -> Array[(String, String)] {"
  echo "  let sources = Array::slice([(\"\", \"\")], 0, 0)"
  echo ""

  for pair in "${BUNDLE_SOURCE_INDEXES[@]}"; do
    local_idx="${pair#*:}"
    echo "  Array::push(sources, source_$local_idx())"
  done

  echo "  sources"
  echo "}"
  echo ""
  echo "export let compiler_source_groups = () -> Array[(String, Array[(String, String)])] {"
  echo "  let groups = empty_grouped_sources()"
  echo ""

  for pair in "${BUNDLE_SOURCE_INDEXES[@]}"; do
    manifest_idx="${pair%%:*}"
    local_idx="${pair#*:}"
    group="${MANIFEST_GROUPS[$manifest_idx]}"
    echo "  push_grouped_source_pair(groups, \"$group\", source_$local_idx())"
  done

  echo ""
  echo "  groups"
  echo "}"
  echo ""
  echo "export let compiler_ordered_sources = () -> Array[(String, String)] {"
  echo "  let sources = Array::slice([(\"\", \"\")], 0, 0)"
  for idx in "${MAIN_ORDERED_INDEXES[@]}"; do
    if local_idx="$(find_bundle_local_index "$idx")"; then
      echo "  Array::push(sources, source_$local_idx())"
    fi
  done
  echo "  sources"
  echo "}"
  echo ""
  echo "export let compiler_ordered_source_groups = () -> Array[(String, Array[(String, String)])] {"
  echo "  let groups = empty_grouped_sources()"
  for pair in "${BUNDLE_SOURCE_INDEXES[@]}"; do
    manifest_idx="${pair%%:*}"
    local_idx="${pair#*:}"
    if is_main_ordered "$manifest_idx"; then
      group="${MANIFEST_GROUPS[$manifest_idx]}"
      echo "  push_grouped_source_pair(groups, \"$group\", source_$local_idx())"
    fi
  done
  echo "  groups"
  echo "}"
} > "$OUT"

echo "Generated $OUT ($(wc -l < "$OUT") lines, $(wc -c < "$OUT" | tr -d ' ') bytes)"
echo "Generated $OUT_ADAPTER ($(wc -l < "$OUT_ADAPTER") lines, $(wc -c < "$OUT_ADAPTER" | tr -d ' ') bytes)"
echo "Generated $OUT_RUNTIME_ENTRY ($(wc -l < "$OUT_RUNTIME_ENTRY") lines, $(wc -c < "$OUT_RUNTIME_ENTRY" | tr -d ' ') bytes)"
