#!/usr/bin/env bash
# Generate selfhost_sources_bundle.vibe — all compiler source files as string constants.
# This allows the selfhost WASM to compile itself without filesystem access.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="${VIBE_SELFHOST_PROJECT_ROOT:-$(dirname "$SCRIPT_DIR")}"
COMPILER_DIR="${VIBE_SELFHOST_COMPILER_DIR:-$PROJECT_ROOT/vibe/compiler}"
MANIFEST="${VIBE_SELFHOST_SOURCE_MANIFEST:-$COMPILER_DIR/selfhost_sources_manifest.tsv}"
OUT="${VIBE_SELFHOST_BUNDLE_OUT:-$COMPILER_DIR/selfhost_sources_bundle.vibe}"

if [ ! -f "$MANIFEST" ]; then
  echo "error: manifest not found: $MANIFEST" >&2
  exit 1
fi

MANIFEST_GROUPS=()
FILES=()
while IFS=$'\t' read -r group relpath; do
  if [ -z "${group}${relpath}" ]; then
    continue
  fi
  case "$group" in
    \#*) continue ;;
  esac
  if [ -z "${relpath:-}" ]; then
    echo "error: invalid manifest row in $MANIFEST: missing path for group '$group'" >&2
    exit 1
  fi
  MANIFEST_GROUPS+=("$group")
  FILES+=("$relpath")
done < "$MANIFEST"

if [ "${#FILES[@]}" -eq 0 ]; then
  echo "error: manifest contains no compiler sources: $MANIFEST" >&2
  exit 1
fi

{
  echo "// AUTO-GENERATED by scripts/generate_selfhost_bundle.sh"
  echo "// Do not edit manually. Regenerate with: bash scripts/generate_selfhost_bundle.sh"
  echo ""
  echo "//# Selfhost source bundle"
  echo ""
  echo "// All compiler source files bundled as (path, source) pairs."
  echo "// Used by selfbuild_compile_stage2 to avoid filesystem access."
  echo "let empty_grouped_sources = () -> Array[(String, Array[(String, String)])] {"
  echo "  Array::slice([(\"\", Array::slice([(\"\", \"\")], 0, 0))], 0, 0)"
  echo "}"
  echo ""
  echo "let push_grouped_source_pair = (groups: Array[(String, Array[(String, String)])], group_name: String, pair: (String, String)) -> Unit {"
  echo "  let (path, source) = pair"
  echo "  let mut i = 0"
  echo "  let mut found = false"
  echo "  while i < Array::length(groups) {"
  echo "    let (name, sources) = Array::get(groups, i)"
  echo "    if String::equals(name, group_name) {"
  echo "      Array::push(sources, (path, source))"
  echo "      found = true"
  echo "      i = Array::length(groups)"
  echo "    } else {"
  echo "      i = i + 1"
  echo "    }"
  echo "  }"
  echo "  if !found {"
  echo "    let sources = Array::slice([(\"\", \"\")], 0, 0)"
  echo "    Array::push(sources, (path, source))"
  echo "    Array::push(groups, (group_name, sources))"
  echo "  }"
  echo "}"
  echo ""

  idx=0
  for f in "${FILES[@]}"; do
    filepath="$COMPILER_DIR/$f"
    if [ ! -f "$filepath" ]; then
      echo "error: file not found: $filepath" >&2
      exit 1
    fi
    relpath="vibe/compiler/$f"
    echo "  let source_$idx = (\"$relpath\","
    # Escape the source code for embedding in a vibe string literal
    # Need to escape: backslash -> \\, double quote -> \", newline -> \n
    python3 -c "
import sys
with open('$filepath', 'r') as f:
    content = f.read()
# Escape for vibe string literal
content = content.replace('\\\\', '\\\\\\\\')
content = content.replace('\"', '\\\\\"')
content = content.replace('\n', '\\\\n')
sys.stdout.write('\"' + content + '\"')
"
    echo ")"
    echo ""
    idx=$((idx + 1))
  done

  echo "export let selfhost_sources = () -> Array[(String, String)] {"
  echo "  let sources = Array::slice([(\"\", \"\")], 0, 0)"
  echo ""

  idx=0
  for _f in "${FILES[@]}"; do
    echo "  Array::push(sources, source_$idx)"
    idx=$((idx + 1))
  done

  echo "  sources"
  echo "}"
  echo ""
  echo "export let selfhost_source_groups = () -> Array[(String, Array[(String, String)])] {"
  echo "  let groups = empty_grouped_sources()"
  echo ""

  idx=0
  for group in "${MANIFEST_GROUPS[@]}"; do
    echo "  push_grouped_source_pair(groups, \"$group\", source_$idx)"
    idx=$((idx + 1))
  done

  echo ""
  echo "  groups"
  echo "}"
} > "$OUT"

echo "Generated $OUT ($(wc -l < "$OUT") lines, $(wc -c < "$OUT" | tr -d ' ') bytes)"
