#!/usr/bin/env bash
# Per-path release census (#2389): of the `let` bindings whose scope-end drop
# a branch merge planned away, how many does the RC lowering's value allow-list
# admit, how much of that the recursive result-spine read is responsible for,
# and what disqualifies the rest? Measurement tool, not a gate.
#
#   bash scripts/path_release_census.sh [flat-source.vibe]
#
# The default input is the flat self-compile source
# (lib/@vibe/compiler/_cli_adapter_module_source.vibe, regenerated by
# scripts/ensure_generated.sh), i.e. the program the compiler builds itself
# from. The probe (scripts/path_release_census_probe.vibe) compiles through the
# committed seed like any `vibe test` file -- it is analysis code importing
# this checkout's planner, so it reports THIS checkout's plan -- and prints one
# row per `PaPathDrop` row; the rows land in _build/path_release_census/rows.tsv
# and a verdict summary on stdout. Row format: see the probe's header.
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

input="${1:-lib/@vibe/compiler/_cli_adapter_module_source.vibe}"
if [ "$#" -eq 0 ]; then
  bash scripts/ensure_generated.sh >/dev/null
fi
[ -s "$input" ] || { echo "path_release_census: input not found or empty: $input" >&2; exit 2; }

out_dir="_build/path_release_census"
mkdir -p "$out_dir"
cp "$input" "$out_dir/input.vibe"

probe="scripts/path_release_census_probe.vibe"
# vibe_test.sh compiles the probe to _build/vibe_test/<path with / as _>.wasm
# and runs it, but discards the run's stdout; rerun the wasm to collect it.
VIBE_TEST_QUIET_COMPILER_NOTE=1 bash scripts/vibe_test.sh "$probe" >/dev/null
wasm="_build/vibe_test/$(printf '%s' "${probe%.vibe}" | tr '/' '_').wasm"
[ -s "$wasm" ] || { echo "path_release_census: probe wasm not produced: $wasm" >&2; exit 1; }
VIBE_PREOPEN_DIR="$ROOT_DIR" bash scripts/run_wasm_vibe_host_runner.sh --invoke _start "$wasm" > "$out_dir/rows.tsv"

echo "[path-release-census] input=$input rows=$(wc -l < "$out_dir/rows.tsv") file=$out_dir/rows.tsv"
echo "[path-release-census] verdicts (FLAT + SPINE = admitted; SPINE = only the recursive result-spine read reaches it):"
awk -F'\t' '{ for (i = 1; i <= NF; i++) if ($i ~ /^verdict=/) print substr($i, 9) }' "$out_dir/rows.tsv" | sort | uniq -c | sort -rn
echo "[path-release-census] SPINE rows by value node kind:"
awk -F'\t' '{ v = ""; t = ""; for (i = 1; i <= NF; i++) { if ($i ~ /^verdict=/) v = substr($i, 9); if ($i ~ /^top=/) t = substr($i, 5) } if (v == "SPINE") print t }' "$out_dir/rows.tsv" | sort | uniq -c | sort -rn
echo "[path-release-census] declined call rows by DECLARED callee contract:"
awk -F'\t' '{ v = ""; c = ""; for (i = 1; i <= NF; i++) { if ($i ~ /^verdict=/) v = substr($i, 9); if ($i ~ /^contract=/) c = substr($i, 10) } if (v == "call" || v == "call_indirect") print c }' "$out_dir/rows.tsv" | sort | uniq -c | sort -rn
echo "[path-release-census] top 25 callees of the declined call class:"
awk -F'\t' '{ v = ""; c = ""; for (i = 1; i <= NF; i++) { if ($i ~ /^verdict=/) v = substr($i, 9); if ($i ~ /^callee=/) c = substr($i, 8) } if (v == "call" || v == "call_indirect") print c }' "$out_dir/rows.tsv" | sort | uniq -c | sort -rn | head -25
