#!/usr/bin/env bash
# Reuse census (ADR-0092 / #2389): how many constructor-rebuild arms of a
# flat source does the Perceus reuse planner pair, and what declines the
# rest? Measurement tool, not a gate.
#
#   bash scripts/reuse_census.sh [flat-source.vibe]
#
# The default input is the flat self-compile source
# (lib/@vibe/compiler/_cli_adapter_module_source.vibe, regenerated by
# scripts/ensure_generated.sh), i.e. the program the compiler builds itself
# from. The probe (scripts/reuse_census_probe.vibe) compiles through the
# committed seed like any `vibe test` file -- it is analysis code importing
# this checkout's planner, so it reports THIS checkout's admission rule --
# and prints one row per arm; the rows land in _build/reuse_census/rows.tsv
# and a verdict summary on stdout. Row format: see the probe's header.
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

input="${1:-lib/@vibe/compiler/_cli_adapter_module_source.vibe}"
if [ "$#" -eq 0 ]; then
  bash scripts/ensure_generated.sh >/dev/null
fi
[ -s "$input" ] || { echo "reuse_census: input not found or empty: $input" >&2; exit 2; }

out_dir="_build/reuse_census"
mkdir -p "$out_dir"
cp "$input" "$out_dir/input.vibe"

probe="scripts/reuse_census_probe.vibe"
# vibe_test.sh compiles the probe to _build/vibe_test/<path with / as _>.wasm
# and runs it, but discards the run's stdout; rerun the wasm to collect it.
VIBE_TEST_QUIET_COMPILER_NOTE=1 bash scripts/vibe_test.sh "$probe" >/dev/null
wasm="_build/vibe_test/$(printf '%s' "${probe%.vibe}" | tr '/' '_').wasm"
[ -s "$wasm" ] || { echo "reuse_census: probe wasm not produced: $wasm" >&2; exit 1; }
VIBE_PREOPEN_DIR="$ROOT_DIR" bash scripts/run_wasm_vibe_host_runner.sh --invoke _start "$wasm" > "$out_dir/rows.tsv"

echo "[reuse-census] input=$input arms=$(wc -l < "$out_dir/rows.tsv") rows=$out_dir/rows.tsv"
echo "[reuse-census] verdicts:"
awk -F'\t' '{ for (i = 1; i <= NF; i++) if ($i ~ /^verdict=/) print substr($i, 9) }' "$out_dir/rows.tsv" | sort | uniq -c | sort -rn
echo "[reuse-census] paired arms by let-spine tail kind (the pre-#2389 tail-only rule paired ctor_same alone):"
awk -F'\t' '{ v = ""; s = ""; for (i = 1; i <= NF; i++) { if ($i ~ /^verdict=/) v = substr($i, 9); if ($i ~ /^spine=/) s = substr($i, 7) } if (v == "PAIRED") print s }' "$out_dir/rows.tsv" | sort | uniq -c | sort -rn
echo "[reuse-census] paired arms by bind modes (c raw transfer, b borrow-only, m/k held):"
awk -F'\t' '{ v = ""; m = ""; for (i = 1; i <= NF; i++) { if ($i ~ /^verdict=/) v = substr($i, 9); if ($i ~ /^modes=/) m = substr($i, 7) } if (v == "PAIRED") { held = (m ~ /[mk]/) ? "held" : "no-held"; print held } }' "$out_dir/rows.tsv" | sort | uniq -c | sort -rn
