#!/usr/bin/env bash
# Rewrite integrations/treesitter-vibe/generated.sha256 from the artifacts on
# disk. Run this ONLY after regenerating all three together -- the stamp is what
# check_treesitter_artifacts.sh compares against, so restamping a half-rebuilt
# tree launders exactly the drift that gate exists to catch (#2409).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
cd "$ROOT"

STAMP="integrations/treesitter-vibe/generated.sha256"

sha256_of() {
  if sha256sum </dev/null >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  elif shasum -a 256 </dev/null >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    echo "sha256sum or shasum is required" >&2; exit 1
  fi
}

{
  echo "# Generated by scripts/stamp_treesitter_artifacts.sh -- do not hand-edit."
  echo "#"
  echo "# The hash each artifact had when all three were last generated from the"
  echo "# same grammar.js. scripts/check_treesitter_artifacts.sh fails when one"
  echo "# moves without the others (#2409)."
  for f in \
    integrations/treesitter-vibe/src/parser.c \
    playground/public/tree-sitter-vibe.wasm \
    integrations/zed-vibe/grammars/vibe.wasm
  do
    [ -f "$f" ] || { echo "missing artifact: $f" >&2; exit 1; }
    echo "$(sha256_of "$f")  $f"
  done
} > "$STAMP"

echo "[stamp-treesitter] wrote $STAMP"
