[package]
name = "xs_core"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
ordered-float.workspace = true
serde = { workspace = true, features = ["derive"] }