[package]
name = "checker"
version.workspace = true
edition.workspace = true

[dependencies]
xs_core.workspace = true
thiserror.workspace = true
ordered-float.workspace = true

[dev-dependencies]
parser = { path = "../parser" }
